### ISSUE TITLE
Create new release 0.5.2 (ios)

### ISSUE THREAD

**Issue by AntoineJac** [prebid/prebid-mobile-ios#111]
@ppuviarasu or @anwzhang , can you please create a new release.

Thanks,

**Comment by AntoineJac** [comment]
@ppuviarasu any updates on this, I am stuck with one RN integration for over a month now...

**Comment by ppuviarasu** [comment]
We will be doing the release on Friday (tomorrow) after notifying the product manager.

**Comment by ppuviarasu** [comment]
The release is completed

**Comment by AntoineJac** [comment]
Thanks a lot for the notification @ppuviarasu
