### ISSUE TITLE
Support Adform Advertising in-app SDK with Prebid

### ISSUE THREAD

**Issue by vladasdrejeris** [prebid/prebid-mobile-ios#112]
We need to have the possibility to deliver ads via Prebid when it is integrated into Adform Advertising in-app SDK. Currently it is not possible to deliver inline ads through prebid and Adform SDK and issues cannot be solved by utilizing already existing adapters of DFP and MoPub. 

#107

**Comment by mjacobsonny** [comment]
@vladasdrejeris -- Thank you for submitting this!  At the moment, we are working on a fairly major overhaul to Prebid Mobile (see: #113 ).  I would recommend that we hold off on this for the immediate term, and we can work with you to ensure that the Adform integration is compatible with Prebid Mobile 1.0.

**Comment by whcemyesil** [comment]
@vladasdrejeris it's probably smart to go with @mjacobsonny's recommendation and wait for Prebid 1.0, however if you need it asap anyway: I've been through the process of making Prebid work with an unsupported ad SDK - email me at cem.yesil@willhaben.at and we can set up a call, maybe I can help you out.

**Comment by ppuviarasu** [comment]
We have revised the SDK to a new simpler version. Do add your integration against the new SDK and submit a PR
