### ISSUE TITLE
ios Bundle field should be itunes id

### ISSUE THREAD

**Issue by AntoineJac** [prebid/prebid-mobile-ios#117]
The current bundle pass to prebid server is the bundleIdentifier. It is all good for android however for iOS as stated in the openRTB doc, the bundle should be the itunes ID.

There are 2 potentials ways of solve this:
- on prebid server by adding the correct bundle in the store request but won’t be correct as it will replace both ios or android -> NOK
- in the prebid SDK (iOS) by either hardcoding the bundle with itunes id (means the app should have been push at least one) or getting it with an api call (http://itunes.apple.com/lookup?bundleId=)

I think hardcode is the best solution as I would like to avoid any loop and call to a the itunes Api.
@mjacobsonny what is your tough about it? 
We could create prebidMobile.bundle = "AppStoreId"

**Comment by AntoineJac** [comment]
@ppuviarasu  and @mjacobsonny ,any update on this. 
This is an important one as DSPs are expected the appStore Id as stated by OpenRtb.
Bid response rate and cpm change could be significant different especially for DSPs like DBM.
This is a direct revenue generating item! 

Thanks,

**Comment by ppuviarasu** [comment]
Hey @AntoineJac We have redesign of the prebidmobile SDK that we are currently working on & that should accept the iTunes id & send it back... 

If the publisher sets the itunesId then we pass in the same else we pass in the bundleID 

Hope this solves the statement

**Comment by ppuviarasu** [comment]
We have fixed this in release #0.5.3

**Comment by matrad** [comment]
@ppuviarasu if we set the itunesID in the App (`Targeting.shared.itunesID = "myItunesId"`), then it's not passed in the prebid-request server-side. The Bundle-ID will be overwritten always and set to `NSBundle.mainBundle`.

I tink [this](https://github.com/prebid/prebid-mobile-ios/blob/2ef315e5954f50ef7e14aa1274d934d293c61166/PrebidMobile/PrebidMobileRendering/Networking/Parameters/PBMAppInfoParameterBuilder.m#L73) is the relevant code part. Here you override the App-Bundle set by [this](https://github.com/prebid/prebid-mobile-ios/blob/2ef315e5954f50ef7e14aa1274d934d293c61166/PrebidMobile/PrebidMobileRendering/Networking/Parameters/PBMParameterBuilderService.m#L118) line.
