### ISSUE TITLE
New release - 5.2.3

### ISSUE THREAD

**Issue by AntoineJac** [prebid/prebid-mobile-ios#121]
Hi @ppuviarasu , can we please make a new release to have the current fix available on cocoapods?
All is ready for the new version 5.2.3 as pushed in the commit:
https://github.com/prebid/prebid-mobile-ios/commit/b47e2fff8d64575649c4dc2e82504226b7e093db

Thanks,

**Comment by ppuviarasu** [comment]
The release will go out today

**Comment by ppuviarasu** [comment]
There is a new release... Thanks for being up on this

**Comment by AntoineJac** [comment]
@ppuviarasu , thanks a lot! 👍  :)
