### ISSUE TITLE
Server response is flaky 

### ISSUE THREAD

**Issue by ignazioc** [prebid/prebid-mobile-ios#145]
I'm trying to integrate this SDK into a black project.
The setup is pretty straightforward:
On the `AppDelegate`

```
PBLogManager.setPBLogLevel(.all)
        let adUnit = PBBannerAdUnit(adUnitIdentifier: "PREBID-MOBILE-SLOT-ID", andConfigId: "7486dd91-d6fc-4622-a7b9-**************")
        adUnit.add(kGADAdSizeMediumRectangle.size)
        PrebidMobile.register([adUnit], withAccountId: "bc1eac66-845e-4d8b-a274-************", with: PBServerHost.appNexus, andPrimaryAdServer: PBPrimaryAdServerType.DFP)
```

then when I need one ad:

```
        PrebidMobile.setBidKeywordsOnAdObject(bannerView,
                                              withAdUnitId: "PREBID-MOBILE-SLOT-ID",
                                              withTimeout: 10000) {

                                                  // add all the keys to the DFP 
                                                  bannerView.load(request)
}
```

The issue I'm finding is that I never get any winner bidder from the API response.

The response looks always like:
```
{
	"id": "0155E2E1-B2D5-4DE8-BF97-014CBBBAF640",
	"ext": {
		"responsetimemillis": {
			"appnexus": 140,
			"rubicon": 153
		},
		"tmaxrequest": 500
	}
}
```

Only once or twice in the previous days I was able to see some winner, can this be a client side integration problem?

thanks

**Comment by GEverding** [comment]
You still having this issue? We’ve been seeing very weird behaviour from prebid on iOS too

**Comment by yoalex5** [comment]
Hello @ignazioc, 

If you have an empty response you can try to use `"test": 1` entry in your request to get more information

**Comment by ignazioc** [comment]
thanks @yoalex5, this issue is almost 1 year old, In the meantime I was able to have a more-or-less working setup. But thanks for your suggestions. I'll keep in mind next time I have to debug
