### ISSUE TITLE
[API 1.0] [MoPub] Banner ad is not rendered properly 

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#150]
Reproduction route: run PrebidDemo -> MoPub -> Simple Banner
Expected result: rendered ad
Actual result: "Hello, I'm not a Prebid ad."
Cause: Keys/Values from PrebidServer response are not passed to MoPub ad request

![img_5d4580aca730-1](https://user-images.githubusercontent.com/8141931/53730694-62c08c00-3e81-11e9-933a-143af558924b.jpeg)

<img width="1552" alt="screen shot 2019-03-04 at 1 30 50 pm" src="https://user-images.githubusercontent.com/8141931/53730882-cba80400-3e81-11e9-9848-d8407fcc6ec0.png">

**Comment by ppuviarasu** [comment]
Approved the PR
