### ISSUE TITLE
[API 1.0] [DFP] Interstitial ad is not rendered properly

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#152]
Reproduction route: run PrebidDemo -> DFP -> Simple Interstitial
Expected result: rendered ad
Actual result: "Prebid Line Items Didn't Serve."
Cause: Keys/Values from PrebidServer response are not passed to DFP ad request

![img_609ed0a3759e-1](https://user-images.githubusercontent.com/8141931/53737347-f059a700-3e94-11e9-891b-a57e10548385.jpeg)

<img width="1552" alt="screen shot 2019-03-04 at 3 50 23 pm" src="https://user-images.githubusercontent.com/8141931/53737462-462e4f00-3e95-11e9-829f-d96a747234e9.png">

**Comment by ppuviarasu** [comment]
Approved the PR
