### ISSUE TITLE
Inventoy Keywords are not present

### ISSUE THREAD

**Issue by AntoineJac** [prebid/prebid-mobile-ios#165]
When looking at the current adUnit api there is a method addUserKeyword (or addUserKeywords) to pass the user targeting to Prebid Server that will passed it to the different bidder as user.keywords

Prebid server is also built to pass inventory keyword to bidder as app.keywords (or site.keywords). However the method in not present in the current adUnit class.

I have run some test with curl and appending the app.keywords and all is working fine, the key value are being passed to Appnexus and Rubicon. So we only need to add the method.

This is important as some publishers want to use inventory targeting to classify their config.

Do notice that it is part of the PR: 164 that I have proposed.

@mjacobsonny , can you please confirm it is fine to add this method.

Thanks

**Comment by ppuviarasu** [comment]
I have fwd this to the product manager... Will get a response and review the PR for the same.
Also do make sure we have the android implementation too for the same before we merge the PR's

**Comment by astephensxandr** [comment]
Hi @AntoineJac I have no problem with adding the method. Perhaps should make it a separate PR from the SwiftLint addition. 

We would also need to make sure the new method is added to the adUnit class documentation.

**Comment by AntoineJac** [comment]
@astephensxandr , thanks here the PR for this issue only:
https://github.com/prebid/prebid-mobile-ios/pull/166

**Comment by AntoineJac** [comment]
@astephensxandr , I have edited also the logic of the methods. Both the user and inventory method are linked to the app level not the adUnit. The methods should be called within the Targeting class.

They are passed in the app.keywords and user.keywords as stated in the openRtb document. With comma as separator. Do notice that normally only a "Comma separated list of keywords" and not keys/value are passed. But it is still possible using addKeywords() method and this allows each bidder to build its adapter to push the data according to its own specs.

- ios PR: #166 
- android: https://github.com/prebid/prebid-mobile-android/pull/95
- github.io edited: https://github.com/prebid/prebid.github.io/pull/1224

Thanks,

**Comment by AntoineJac** [comment]
@astephensxandr , @ppuviarasu , @mjacobsonny 
Regarding these PR about keywords/data, we are currently thinking about standardizing it so we are sure to be all able to ingest it. This is the current "intent to implement". Could you please have a look at it and tell us what you think? Thanks,
https://github.com/prebid/Prebid.js/issues/3687

**Comment by bszekely1** [comment]
Closing this in favor of supporting a common first party data method.
