### ISSUE TITLE
Google-Mobile-Ads-SDK v7.42.0 terminates the app

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#169]
<img width="1134" alt="Screen Shot 2019-04-01 at 12 57 47 PM" src="https://user-images.githubusercontent.com/8141931/55320371-917d5280-547f-11e9-9ab2-dcf04fc721fd.png">

[Release notes](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/rel-notes)
[Get started](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/quick-start)

**Comment by AntoineJac** [comment]
As explained below it can be fixed by adding GADIsAdManagerApp key with a boolean value YES to your app's Info.plist:
<img width="795" alt="Screenshot 2019-04-03 at 11 40 36" src="https://user-images.githubusercontent.com/23024588/55451400-5311a000-5605-11e9-8727-e38d515683bb.png">

**Comment by yoalex5** [comment]
changes are in as part of this PR #173
