### ISSUE TITLE
bid requests by default set the user gender to "F"

### ISSUE THREAD

**Issue by nanek** [prebid/prebid-mobile-ios#17]
According to the logs bid requests by default set the user gender to `F`. I believe the default should be `O` for unknown.

Easily fixed by setting `[[PBTargetingParams sharedInstance] setGender:PBTargetingParamsGenderUnknown];` however based on the docs I'd expect this to be the default.

**Comment by nhedley** [comment]
@nanek I just merged a fix for this. Thanks for catching the bug.
