### ISSUE TITLE
UI API called on background thread

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#172]
When PBServer response code is not success we receive this warning 

<img width="1134" alt="Screen Shot 2019-04-01 at 2 33 15 PM" src="https://user-images.githubusercontent.com/8141931/55328514-37878780-5495-11e9-99da-9ced18209041.png">

**Comment by ppuviarasu** [comment]
when is this crash happening?

Can you reproduce the steps?

when you call register on PBM or when you call loadAd of MoPub loadAd

**Comment by ppuviarasu** [comment]
Merged the PR
