### ISSUE TITLE
Module 'PrebidMobile' not found

### ISSUE THREAD

**Issue by rochapablo** [prebid/prebid-mobile-ios#182]
I'm not able to import PrebidMobile.

This is what I did:

```
$ pod init
```

``` pod 'PrebidMobile' ``` inside my Podfile and ``` $ pod install ```.

When I try to import ``` @import PrebidMobile; ```, I get:

```
Module 'PrebidMobile' not found
```

```
Xcode 10.2.1
```

**Comment by lilahunt** [comment]
Hi rochapablo, looking into it.

**Comment by ppuviarasu** [comment]
@rochapablo Did you uncomment `use frameworks` in your pod file?
I tried downloading the PrebidMobile into a new project and it worked just fine.
Try doing the same and let us know if any issues

**Comment by rochapablo** [comment]
In my pod file `use_frameworks` it's commented: `# use_frameworks!`, because I'm not using Swift.

I also notice that in the example it seems to work only because it has PrebidMobile inside PrebidDemo, am I wrong? Shouldn't be working only by adding by pod?

Anyway, I'm trying to working with something a little different from the example, I'm creating a custom React Native Module to implement PrebidMobile.

**Comment by rochapablo** [comment]
If I add `$(BUILT_PRODUCTS_DIR)/PrebidMobile` to `Search Paths > Framework Search Paths` the `Module 'PrebidMobile' not found` error gets fixed. But it new ones appears:

```
Prebid.shared.prebidServerAccountId = _prebidServerAccountId;
// (!) Use of undeclared identifier 'Prebid'

Prebid.shared.prebidServerHost = PrebidHostAppnexus;
// (!) Use of undeclared identifier 'Prebid'

Prebid.shared.shareGeoLocation = true;
// (!) Use of undeclared identifier 'Prebid'
``` 

```
self.bannerUnit = [[PBBannerAdUnit alloc] initWithConfigId:_prebidConfigId size:CGSizeMake(320, 50)];
// (!) No visible @interface for 'PBBannerAdUnit' declares the selector 'initWithConfigId:size:'
```

```
[self.bannerUnit setAutoRefreshMillisWithTime:35000];
// (!) No visible @interface for 'PBBannerAdUnit' declares the selector 'setAutoRefreshMillisWithTime:'
```

And yes, I'm importing `PrebidMobile`

```
@import PrebidMobile;
```

So what could I be doing wrong?

**Comment by AlexKar** [comment]
+1, we have the same problem after update to xcode 10.2.1

**Comment by ptomasroos** [comment]
The reason behind this is that one needs to use 

```
use_frameworks
```

Because Prebid has been rewritten in Swift.

Cocoapods doesn't support both frameworks and static libraries (objective-c libs) And in our case we have other dependencies which are static libraries, hence there is no upgrade path for us. (We're running a objective-c app).

Again we're depending on Firebase (quite a large dependency in many apps considerings its google's infrastructure) and still the decision was to move on to Swift with PrebidMobile. Problems for us Publishers, perhaps better for maintainers with less users :)

**Comment by rochapablo** [comment]
I tried `use_frameworks!` but unfortunately I still having [those errors](https://github.com/prebid/prebid-mobile-ios/issues/182#issuecomment-493027454).

**Podfile**
```
target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for example

  pod 'Google-Mobile-Ads-SDK'
	pod 'PrebidMobile'
end
```

**Comment by AntoineJac** [comment]
Explanation here:
https://github.com/CocoaPods/CocoaPods/issues/7835

You need to remove any input file list or output file list. You also may then need to clean your project file, in prebid-mobile-ios/example/ObjectiveC or prebid-mobile-ios/example/Swift:
- use pod deintegrate
- delete all pod remains files - Podfile.lock, Pods, <Project>.xcworkspace
- open <Project>.xcodeproj
- remove Pods project on left side
- try pod install

@yoalex5 and @ppuviarasu  , to avoid such issues should we only push the examples with pod and without the podfile.lock and pods directory? We will also need to clean the pbxproj file.

**Comment by bszekely1** [comment]
Hello @rochapablo is this issue still outstanding? I would like to close it if it's addressed.

**Comment by rochapablo** [comment]
Hello @bszekely1. The issue still.

**Comment by rochapablo** [comment]
Turns out that the problem was with my podspec. When creating the react-native module the podspec file should be moved to root folder.
