### ISSUE TITLE
Prebid using DFP BannerViews - Updated Google Mobile Ads SDK

### ISSUE THREAD

**Issue by ctherkelsen** [prebid/prebid-mobile-ios#185]
Hello, 

We are currently using the Prebid mobile SDK in our iOS app. Its been live for some time without any issues. However we recently updated the Google Mobiles Ads SDK and this caused Prebid to stop working. When debugging with Charles we see no bids sent to AppNexus. If we roll back to and older Google Mobile Ads SDK it works again. 

My question is, if there are any known issues regarding this? We are using Prebid mobile 0.5.3

**Comment by AntoineJac** [comment]
Hi @ctherkelsen , thank you for reporting this. 
The issue here is Google having updating their method or class name and as previous Prebid SDK was relying on swizzling it is no more working. As Prebid Mobile 0.X is no more supported, please migrate to Prebid 1.X. It should work fine.

Thanks,
