### ISSUE TITLE
Intent to implement: iOS support for domain and iTunes store URL

### ISSUE THREAD

**Issue by bszekely1** [prebid/prebid-mobile-ios#188]
## Type of issue
Intent to implement

## Description
The goal of this ticket is to provide iOS support for application domain and app store URL targeting. Both fields are typically passed to DSPs for targeted and are supported in the Android implementation.

### SDK API interface
The below proposal are the fields to the SDK API interface for publishers:

**Store URL**
Proposal
`Targeting.shared.storeURL`

**Domain**
proposal
`Targeting.shared.domain`

### OpenRTB interface to PBS
The Prebid SDK will create an OpenRTB request to Prebid server with domain and app store URL. Both fields are already defined in OpenRTB 2.5, keeping the same protocol design to PBS.

**Domain example**
```  
	"app": {
		"bundle": "com.Prebid.PrebidDemo",
                "domain": "appdomain.com",
		"ver": "0.1",
		"publisher": {
			"id": "1234"
		}
``` 

**Store URL example**
```  
	"app": {
		"bundle": "com.Prebid.PrebidDemo",
                "storeurl": "https://itunes.apple.com/app/id548572622",
		"ver": "0.1",
		"publisher": {
			"id": "1224"
		}
```  

## Platform details

iOS only. Android supports these fields.

## Other information

The origin desire to implement this feature was defined in the [version 1.0 update](https://github.com/prebid/prebid-mobile-ios/issues/113), however these fields were left out.

**Comment by yoalex5** [comment]
The public API looks like:
```
    Targeting.shared.storeURL = "https://itunes.apple.com/app/id123456789"
    Targeting.shared.domain = "appdomain.com"
```
