### ISSUE TITLE
UnitTests are broken

### ISSUE THREAD

**Issue by ThomWee** [prebid/prebid-mobile-ios#192]
I forked the project while updating the Swift support and need some further tweaks. But while doing so I came across the situation, that some tests are not working.

**Steps to reproduce**
Check out master. First Fix the `PrebidServerOneBidFromAppNexusOneBidFromRubicon.json` source path, since this is taken from the android project. After doing so and run all test the test `func testBidManagerRequestForBidResponseFromTwoBidders()` starts to fail: keyword.count is 15 and not as expected 16.

Now I changed the test scheme to run tests in random order and got 7 more tests failing.

Can you fix the tests so that I can continue on my fork to see that I don't break anything!?

**Comment by yoalex5** [comment]
@ThomWee, I had fixed critical issues with UnitTests ant they have been merged to master. 

I am going to close this issue as well as create a new ticket with running UnitTest in random order #200
