### ISSUE TITLE
Support for iOS 9.0 (or iOS 10.0)

### ISSUE THREAD

**Issue by peterhaldbaek** [prebid/prebid-mobile-ios#206]
I initially wanted to comment on #167 but was not allowed to (probably because it is closed). Is there any chance you might reconsider adding support for iOS 9.0? I understand the argument about not wanting to spend resources on testing on platforms which are soon dead anyway but ignoring 5% users is equal to ignoring 5% revenue. We are still seeing some traffic from iOS 10 specifically.

**Comment by bszekely1** [comment]
We have reconsidered supporting iOS 9.0. There is a patch release coming out this week that will include support for 9.0+.

**Comment by yoalex5** [comment]
PR #207

**Comment by yoalex5** [comment]
iOS 9 support was added to [1.1.1 release](https://github.com/prebid/prebid-mobile-ios/releases/tag/1.1.1)
