### ISSUE TITLE
Int.max overflow

### ISSUE THREAD

**Issue by ton-impalastudios** [prebid/prebid-mobile-ios#209]
On 32-bit devices like iPhone 5c, the method `getCurrentMilis` in the `BidManager` causes a overflow of Int.max.

**Comment by lilahunt** [comment]
@ton-impalastudios thanks for submitting we'll take a look.

**Comment by AntoineJac** [comment]
I confirm the issue, replacing with Int64 will fix. Here is the PR: #211 

@yoalex5 , I let you decide if we should fix this or not. I checked on google and iphone 5c and lower are representing small % of the traffic.
