### ISSUE TITLE
Initalizing PrebidMobile iOS swift

### ISSUE THREAD

**Issue by 10686142** [prebid/prebid-mobile-ios#210]
Maybe I am looking at an outdated documentation ,so please correctly me if I am wrong: http://prebid.org/prebid-mobile/pbm-api/ios/code-integration-ios.html. And I also looked at this iOS swift example which stated the same thing: https://github.com/prebid/prebid-mobile-ios/blob/master/example/Swift/PrebidDemo/PrebidDemo/AppDelegate.swift

Eitherway, instantiating Prebid in that manner is not possible, since I only see PrebidMobile avilable instead of just Prebid. 

So after looking at some of the possible functions to instantiate PrebidMobile in my AppDelegate I saw the PrebidMobile.register() method, where I can also pass on the serverID and accountID, but the problem there is that I get an error when I try to instantiate it becaue the banner has no size specified:

` let bannerUnit = PBAdUnit(identifier: "/test/my-size-rectangle", andAdType: .banner, andConfigId: "my-config-id")`
 ` PrebidMobile.register([bannerUnit], withAccountId: "my-account-id", with: .appNexus, andPrimaryAdServer:.unknown)`

And this is the error I get: 
` 'PBAdUnitNoSizeException', reason: 'Ad unit size object is not specified.' `

So my first though was to add a size, since when I look at the code for a PBAdUnit, I saw that adsizes is also an available parameter:
`@interface PBAdUnit : NSObject`
.....
` @property (nonatomic, readonly) NSArray<CGSize> *__nullable adSizes;`

But somehow I can't get that to work, probably also because I never coded Objective-C, so I am not sure what the difference is between the adSizes and the rest of the available parameters for a PBAdUnit like this one:
` @property (nonatomic, readonly) NSString *__nullable configId; `

Bottomline is, how do I correctly initialise PrebidMobile? Or how do I get the Prebid methods to work, which are also specified in the documentation?

Thanks in advance for any help!

**Comment by AntoineJac** [comment]
@10686142 , this is a little confusing. Are you sure to use the last documentation that you can find on:
http://prebid.org/prebid-mobile/pbm-api/ios/pbm-bannerad-ios.html

Prebid 1.X is no more using the register method and PBAdUnit class. Also I do confirm that you need to import PrebidMobile but the public class of it is called Prebid

Thanks,

**Comment by 10686142** [comment]
My bad for my half explanation; The problem for me lies in the AppDelegate upon initialising PrebidMobile, because I get the error "No such module 'Predbid'" when I try to import Predbid instead of PrebidMobile. The screenshot is in the attachments.

So basically the steps I explained I took, are because I am using the PrebidMobile class after installing the Pod, since I can't seem to import Prebid instead. So than I tried to initialise the PrebidMobile class instead.

But probably the best solution for me is to figure out how I can actually use Prebid itself, so I can just follow your docs.

Eitherway, do you perhaps know how I can make the Prebid class work?

________________________________
Van: Antoine Jacquemin (Rubicon) <notifications@github.com>
Verzonden: woensdag 19 juni 2019 11:04
Aan: prebid/prebid-mobile-ios
CC: 10686142; Mention
Onderwerp: Re: [prebid/prebid-mobile-ios] Initalizing PrebidMobile iOS swift (#210)


@10686142<https://github.com/10686142> , this is a little confusing. Are you sure to use the last documentation that you can find on:
http://prebid.org/prebid-mobile/pbm-api/ios/pbm-bannerad-ios.html

Prebid 1.X is no more using the register method and PBAdUnit class. Also I do confirm that you need to import PrebidMobile but the public class of it is called Prebid

Thanks,

**Comment by AntoineJac** [comment]
Hi @10686142 , are you trying to import it using Cocoapods or after building the framework from source? I'd recommend using pod, you can then directly use the Prebid class.

**Comment by 10686142** [comment]
I installed the PrebidMobile via Pod. But the weird things is that created a new App and also added the PrebidMobile pod in there, and in there I can access the Prebid class. Also when I look at the pods code files they're completely different. I added the screenshots in the attachments.

Do you guys know by any chance how these Apps could have installed different Pod files while referencing the same Pod in the Podfile?

________________________________
Van: Antoine Jacquemin (Rubicon) <notifications@github.com>
Verzonden: woensdag 19 juni 2019 13:19
Aan: prebid/prebid-mobile-ios
CC: 10686142; Mention
Onderwerp: Re: [prebid/prebid-mobile-ios] Initalizing PrebidMobile iOS swift (#210)


Hi @10686142<https://github.com/10686142> , are you trying to import it using Cocoapods or after building the framework from source? I'd recommend using pod, you can then directly use the Prebid class.

**Comment by AntoineJac** [comment]
@10686142 , unfortunately I don't see the attachment but in all case I would suggest you to remove all the pod files and re install it :
- use pod deintegrate
- delete all pod remains files - Podfile.lock, Pods, .xcworkspace
- open .xcodeproj
- remove Pods project on left side
- try pod install

You pods file should included:
`target 'PrebidDemo' do
  use_frameworks!

  # Pods for PrebidDemo
  pod 'Google-Mobile-Ads-SDK'
  pod 'PrebidMobile'
end`

**Comment by 10686142** [comment]
Thanks for your help, do you know how I can reply to this on Github?
Because every time I try, I get the message "You can't comment at this time."

________________________________
Van: Antoine Jacquemin (Rubicon) <notifications@github.com>
Verzonden: donderdag 20 juni 2019 04:34
Aan: prebid/prebid-mobile-ios
CC: 10686142; Mention
Onderwerp: Re: [prebid/prebid-mobile-ios] Initalizing PrebidMobile iOS swift (#210)


@10686142<https://github.com/10686142> , unfortunately I don't see the attachment but in all case I would suggest you to remove all the pod files and re install it :

  *   use pod deintegrate
  *   delete all pod remains files - Podfile.lock, Pods, .xcworkspace
  *   open .xcodeproj
  *   remove Pods project on left side
  *   try pod install

You pods file should included:
`target 'PrebidDemo' do
use_frameworks!

Pods for PrebidDemo

pod 'Google-Mobile-Ads-SDK'
pod 'PrebidMobile'
end`

**Comment by AntoineJac** [comment]
Clean cookies and try again and make sure your adblocker is not activate ;)

**Comment by 10686142** [comment]
Alright got it figured out, somehow a different non working version get's installed when you haven't changed your project's Deployment s on instalment for iOS < 11.

If you also don't want to have to update your whole project to iOS 11, just to be able to use this pod:

**Before Installation**
-> You do need to have your project set to Swift version 4.2, and therefore at least Xcode 9.
-> This worked for me on my deployment taget of iOS 10.0, I am not sure about version lower than 10.
-> Make sure in your project's settings, you have set your deployment target to iOS 11 or up, this is only when for when you're going to run the pod update or install.

**Installation**
Run pod install or update

**After installation**
1) Optional: You can get a warning about an unrecognised version of Swift, version 5, if you're not in an Xcode version above 9. This is what you need to do than:
-> Click on the Pods target
-> Select the PrebidMobile Pod
-> Go to Build Settings
-> Set the "Swift Language Version" to 4.2
![Screen Shot 2019-06-20 at 16 08 57](https://user-images.githubusercontent.com/23178404/59856449-36b91000-9377-11e9-8465-2edaf17bfe1d.png)
This pod's Swift version however can't be lower than 4.2 due to some functions used.

2) Than (still) in the pod settings, click on the General tap, and change the Pod's deployment target to the one you're also going to set your project to:
![Screen Shot 2019-06-20 at 16 54 36](https://user-images.githubusercontent.com/23178404/59859234-a8e02380-937c-11e9-838c-a58a53cd982a.png)

3) Than you can set your projects Deployment Target back to your original one.


**A few notes:**
-> Setting the pod's platform :ios, '11.0', wasn't sufficient for me to get the right version installed.
-> You have to **set your Deployment target to iOS 11 and up on every pod update**. The newer version of the Prebid Pod got replaced by an older one when I used the pod update.


Good luck!
