### ISSUE TITLE
Can't access shared singleton on Utils in objective-c on version 1.1.1

### ISSUE THREAD

**Issue by ptomasroos** [prebid/prebid-mobile-ios#215]
![Screenshot 2019-07-03 at 19 38 43](https://user-images.githubusercontent.com/1064547/60613420-24a18d80-9dcb-11e9-9a6e-935f2a843dd4.png)
![Screenshot 2019-07-03 at 19 38 56](https://user-images.githubusercontent.com/1064547/60613426-279c7e00-9dcb-11e9-8449-b394788ba1b4.png)

With the latest support of CreativeResizing that was added to Utils its not possible to invoke it through Objective-c for some reason.

**Comment by yoalex5** [comment]
@ptomasroos, we have merged the changes to master branch and it will be a part of v1.2 release. 
Please check it and reopen the issue if necessary
