### ISSUE TITLE
Objective-C LogLevel support

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#223]
The PR #217 exposes `LogLevel` that is String Enum. 
But Objective-C supports only Int Enums as a result it is not possible to use a public loglevel feature from Objective-C code

<img width="1083" alt="Screen Shot 2019-07-23 at 4 14 24 PM" src="https://user-images.githubusercontent.com/8141931/61715072-f88f8180-ad64-11e9-9d9f-cb67d752687e.png">

**Comment by bszekely1** [comment]
PR was merged. Closing this issue
