### ISSUE TITLE
Running sample app in Swift, received error unable to open file Pods-PrebidDemo

### ISSUE THREAD

**Issue by schoenbl** [prebid/prebid-mobile-ios#224]
I tried to launch the demo Swift app by opening:
prebid-mobile-ios-master > example > Swift > PrebidDemo

When I attempt a build, I receive an error of:

/Users/schoenbl/Downloads/prebid-mobile-ios-master/example/Swift/PrebidDemo/Pods/Target Support Files/Pods-PrebidDemo/Pods-PrebidDemo.debug.xcconfig: unable to open file (in target "PrebidDemo" in project "PrebidDemo") (in target 'PrebidDemo')

When I look down that file path, under Target Support Files, Pods-PrebidDemo is not there.

**Comment by bszekely1** [comment]
Hi @schoenbl, what version of the Prebid SDK have you attempted to compile? What version of iOS have you tested this on?

**Comment by schoenbl** [comment]
@bszekely1 I resolved the issue. Once the pods were installed, the issue went away. Thanks.
