### ISSUE TITLE
Could not find module 'PrebidMobile' for architecture 'x86_64'; found: arm64

### ISSUE THREAD

**Issue by Jobeso** [prebid/prebid-mobile-ios#234]
First of all, I think the Prebid project is awesome, so thank you all for that!

Now to my problem:
I was trying to integrate PrebidMobile as a Pod but ran into build issues when enabling `use_frameworks` and I was not able to import PrebidMobile without this. I also followed the deployment target adjustments from #210 and the pod deintegration from #182 but nothing helped, I still ran into build issues.

So I tried to manually implement the framework. After downloading and building the framework according to the readme, I copied it with "Copy items if needed" and added it to the "Embedded Binaries" section. Now I am able to import PrebidMobile but run into a build issue `Could not find module 'PrebidMobile' for architecture 'x86_64'; found: arm64` when building a Debug build to both simulator and physical device.
My attempt to fix this was setting `Build Active Architecture Only` to `No` and add `i386` and `x86_64` to `Valid Architectures` in the Build Settings. Unfortunately, it didn't help.

Does anyone know how to approach this?

**Comment by yoalex5** [comment]
Hello @Jobeso !

I would prefer using `CocoaPods` as dependency manager.
Could you please add the information about your envirompment, `Podfile` and build issues that you have run into?

Thanks

**Comment by yoalex5** [comment]
Hello @Jobeso !

The error `Could not find module 'PrebidMobile' for architecture 'x86_64'; found: arm64` should be fixed into the next release

**Comment by Jobeso** [comment]
Hey @yoalex5,
thanks for letting me know. I'll try it out. Unfortunately, I am currently not able to use it as a pod but this has nothing to do with the repo.

**Comment by yoalex5** [comment]
Good. In any case you are able to use `PrebidSDK` source code as a dependency in your project/workspace
