### ISSUE TITLE
iOS deprecated UIWebView API usage warning

### ISSUE THREAD

**Issue by PatrickDotStar** [prebid/prebid-mobile-ios#236]
>ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Apple will, probably with the release of iOS 13, no longer accept builds that make use of deprecated UIWebView in favor of using WKWebView.
There are still some UIWebView usages within the Prebid SDK for eg in `AdViewUtils.swift`

**Comment by bszekely1** [comment]
Hi Patrick,

Thanks for submitting this issue. I will circle back internally on addressing this issue.

**Comment by bszekely1** [comment]
After reviewing internally, we use UIWebView to resize ad slots when Google Ad Manager (Google Mobile Ads SDK) renders ads. The Google Mobile Ads SDK uses UIWebView as a function to derive the size of the ad. This issue should be taken up with the Google Mobile Ads SDK team for them to WKWebView instead. Once done we can support both new and old methods.

**Comment by ThomWee** [comment]
https://developers.google.com/admob/ios/rel-notes

Since 4.2.2020 is officially UIWebView removed from the SDK. Can you reconsider to remove the code lines of the SDK!? @bszekely1

Also was before an option in place to tell the SDK to only use WKWebViews instead of UIWebView.

**Comment by PatrickDotStar** [comment]
There are still some UIWebViews available in code what I see. All of them should to be replaced with WKWebView otherwise we keep getting the warning from Apple.

<img width="867" alt="UIWebView" src="https://user-images.githubusercontent.com/10392878/76297538-43d8af00-62b8-11ea-8860-665b6d9a1d7e.png">

**Comment by bszekely1** [comment]
Removing functionality of UIWebView may cause certain version of the Google Ad Manager SDK to break. When we last checked on this issue some weeks (months?) ago, GAM's SDK did not support WKWebView, causing a dependency on UIWebView. We are going to to another investigation on the most recent versions of GAM's SDK to see if we can remove any UIWebView reference and support "X" version of GAM going forward. Something we are evaluation.
