### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ismetanin** [prebid/prebid-mobile-ios#245]
Hi! It'd super cool to use prebid-mobile with Carthage

**Comment by bszekely1** [comment]
What advantages do you see for prebid mobile to use Carthage?

**Comment by ismetanin** [comment]
@bszekely1 
A lot of projects use Carthage and mine too, it would be at least convenient

**Comment by eduardo22i** [comment]
@bszekely1 not all developers use Cocoapods. Btw, Any plan to integrate **Swift Package Manager**?  😄 (Should I create another issue?)

**Comment by bszekely1** [comment]
We are always looking for contributors. If you have ideas and wish to contribute, please feel free draft up some ideas and collaborate.
