### ISSUE TITLE
Prebid Mobile Native In App Rendering

### ISSUE THREAD

**Issue by anwzhang** [prebid/prebid-mobile-ios#260]
## Type of issue
Intent to implement

## Description
With release 1.4, publisher now can render native assets inside banner. However we would still want to provide the experience of rendering native assets the native way.

## Goals
- Provide APIs to provide assets to the publisher for native rendering.
- Track the rendered views and log impressions accordingly
- Click handling and click tracking 

## Tech Spec
See attachment
[CT-PrebidMobileNativeInAppRendering-090120-1936-952.pdf](https://github.com/prebid/prebid-mobile-ios/files/4042147/CT-PrebidMobileNativeInAppRendering-090120-1936-952.pdf)

**Comment by ppuviarasu** [comment]
added and released in v1.10
