### ISSUE TITLE
+[AdViewUtils findPrebidCreativeSize:success:failure:] always fails

### ISSUE THREAD

**Issue by muccy** [prebid/prebid-mobile-ios#263]
**Describe the bug**
After ad loader calls delegate method `-adLoader:didReceiveDFPBannerView:`, invocation of class method `+[AdViewUtils findPrebidCreativeSize:success:failure:]` always leads to failure block. The method emits `[⚠️][AdViewUtils.swift]:51 24 warnAndTriggerFailure(_:failure:) -> The view doesn't include WebView`, which is proper since view only contains a `GADWebAdView`, that seems not to be a subclass of `UIWebView` or `WKWebView`. As a result, I get a 1x1 banner view on screen.
Here's recursive description of received banner view:
```
po [bannerView recursiveDescription]
<DFPBannerView: 0x12bd344a0; frame = (0 0; 300 250); clipsToBounds = YES; layer = <CALayer: 0x281ea6e00>>
   | <DFPInternalBannerView: 0x12bd962d0; frame = (0 0; 300 250); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x281ea6c00>>
   |    | <GADContainerAdView: 0x12bea9750; frame = (0 0; 300 250); gestureRecognizers = <NSArray: 0x2810120a0>; layer = <CALayer: 0x281e6e3c0>>
   |    |    | <GADSizedAdView: 0x12bea9af0; frame = (0 0; 300 250); layer = <CALayer: 0x281e6e440>>
   |    |    |    | <GADSwappableView: 0x12bea93c0; frame = (0 0; 300 250); autoresize = LM+RM+TM+BM; layer = <CALayer: 0x281e6e3e0>>
   |    |    |    |    | <GADWebAdView: 0x12be90820; frame = (0 0; 300 250); autoresize = W+H; gestureRecognizers = <NSArray: 0x281013d50>; layer = <CALayer: 0x281e6d5e0>>
   |    |    |    |    |    | <UIScrollView: 0x12c0ec800; frame = (0 0; 0 0); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x28101b1b0>; layer = <CALayer: 0x281e6d5c0>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}>
```

**To Reproduce**
1. `GADRequest *request = [GADRequest request];`
2. `[self.prebidAdUnit fetchDemandWithAdObject: request  completion:...]`
3. In `-[fetchDemandWithAdObject:completion:]` completion block, call `[self.adLoader loadRequest:request];`
4. In `<DFPBannerAdLoaderDelegate>` method `-[adLoader:didReceiveDFPBannerView:]`, invoke `+[AdViewUtils findPrebidCreativeSize:success:failure:]`

**Expected behavior**
`+[AdViewUtils findPrebidCreativeSize:success:failure:]` should help to resize DFP banner views that contain `GADWebAdView` instances.

**Versions:**
 - iOS 13.3
 - Xcode 11.3
 - PrebidMobile 1.3 (CocoaPods)
 - Google Ads 7.52.0

**Comment by marcelklinek** [comment]
I can confirm this behaviour. Right now I’m resizing manually, as described in https://github.com/prebid/prebid-mobile-ios/issues/175#issuecomment-491356278
In short, on iOS I used
```
self.dfpBanner.resize(bannerView.adSize)
```
In my case, Prebid creative indeed does not render unless resized.

**Comment by yoalex5** [comment]
Hello @muccy,

Today I setup DemoApp with `adLoader` and could not reproduce this issue.
Could you please specify your envirompment:
```
ServerHost
ServerAccountId
ConfigId
AdUnitID
```

As for `GADWebAdView` it is container which should has a `WebView` inside
<img width="193" alt="Screenshot 2020-01-13 at 14 51 00" src="https://user-images.githubusercontent.com/8141931/72257528-8b262480-3614-11ea-9870-49b5b5820f7f.png">

**Comment by muccy** [comment]
Problem is `GADWebAdView` is not a web view:
```
(lldb) po NSClassFromString(@"GADWebAdView")
GADWebAdView
(lldb) p [NSClassFromString(@"GADWebAdView") isKindOfClass:UIWebView.class]
(BOOL) $2 = NO
(lldb) p [NSClassFromString(@"GADWebAdView") isKindOfClass:WKWebView.class]
(BOOL) $3 = NO
```

* ServerHost = `Appnexus`
* ServerAccountId = `399f131e-2292-4892-9018-dd8f4e7dd11d`
* ConfigId = `62b0ff1e-4b73-4a71-a836-d774c1ffeac5`
* AdUnitID = `/1020895/TMWNET_APP_300x250_Read` (it's a AdManager position)

Thank you, bye

**Comment by yoalex5** [comment]
Hello @muccy 

I have tried your setup and still can not reproduce the issue. Usually I get 
```
The HTML doesn't contain a size object
```

Could you please add a Charles log to analyse it

**Comment by muccy** [comment]
I suspect you cannot reproduce error because we use an AdManager account. Full app configuration in Info.plist is:
* bundle identifier: `it.tcc.tmw`
* `GADIsAdManagerApp` = `YES`
* `gad_preferred_webview` = `wkwebview`

I will get back as soon I succeed logging something useful with Charles. Thank you

**Comment by muccy** [comment]
I've made two tests:
1. no SSL proxy hosts specified to Charles: I got only NoBids, unfortunately
2. SSL proxy hosts specified to Charles: timeouts

Anyway I'll attach you Charles files.
Thank you, bye

[Prebid.zip](https://github.com/prebid/prebid-mobile-ios/files/4103858/Prebid.zip)

**Comment by yoalex5** [comment]
Hello @muccy,

Thanks for your logs. 
We should [setup Charles properly](https://www.detroitlabs.com/blog/2018/05/01/how-to-set-up-charles-proxy-for-an-ios-simulator/) to analyse a log. 
As I see you use a simulator:

1. Install RC 
`Help -> SSL Proxying -> Install Charles Root Certificate in iOS Simulators`
2. Enable macOS proxy
`Proxy -> macOS Proxy`
3. Check SSL Proxying
`Proxy -> SSL Proxy Settings...`
4. Restart Simulator and Charles

**Comment by muccy** [comment]
Thank you very much for directions: now SSL Proxying works correctly. If you need, I can also test on device.
I attach you Charles log, even if I can't still get successful bid.
Bye
[NoBids.chls.zip](https://github.com/prebid/prebid-mobile-ios/files/4107684/NoBids.chls.zip)

**Comment by yoalex5** [comment]
@muccy, are you sure that previously you got a successful bid(not empty) and `The view doesn't include WebView` error ? Because `findPrebidCreativeSize` function only works in tandem with not empty `auction` response.

If not, please help to reproduce this issue.
Thanks

**Comment by muccy** [comment]
120% sure I've got `prebidDemandFetchSuccess`. It's only bad luck now. If you have some test configuration to get successful auction, I would be happy to apply that one.
Bye

**Comment by yoalex5** [comment]
You can find a next setup in DemoApp
```
ServerHost = Appnexus
ServerAccountId = bfa84af2-bd16-4d35-96ad-31c6bb888df0
ConfigId = 6ace8c7d-88c0-4623-8117-75bc3f0a2e45
AdUnitID = /19968336/PrebidMobileValidator_Banner_All_Sizes
```

**Comment by muccy** [comment]
Ok, thank you. I applied demo settings (excluding AdUnitID) and I discovered something really really strange. With _Debug View Hierarchy_ tool I found a `WKWebView` instance inside `GADWebView`, but resize function still does not succeed.
![Schermata 2020-01-28 alle 09 31 25](https://user-images.githubusercontent.com/18466/73247883-28a35b80-41b2-11ea-846c-79f436e6c2e1.png)

So I put a breakpoint in `findWebView(_:closure:)` when `subview` is `GADWebView`. I expected two subviews, but...
```
po subview.subviews
▿ 1 element
  - 0 : <UIScrollView: 0x7fbfd4067e00; frame = (0 0; 0 0); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x60000389adc0>; layer = <CALayer: 0x600003641140>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}>
```

I don't know if you are still interested in, but I'll attach you Charles log file. As soon as I can, I'll try to attach you a demo Xcode project in order to reproduce behaviour.
Thanks, bye
[AuctionSuccess.chls.zip](https://github.com/prebid/prebid-mobile-ios/files/4121421/AuctionSuccess.chls.zip)

**Comment by muccy** [comment]
Here's demo project that replicates issue at any banner load request.
Thank you, bye
[PrebidResizeBug.zip](https://github.com/prebid/prebid-mobile-ios/files/4121659/PrebidResizeBug.zip)

**Comment by yoalex5** [comment]
Hello @muccy 

As for your `PrebidResizeBug` project. 
1. `GADWebAdView` does not contain a `WebView` because you have not added it.
2. `findPrebidCreativeSize()` function returns a `size` which you should apply for a banner

I made some changes:

<img width="1440" alt="Screenshot 2020-01-29 at 15 02 50" src="https://user-images.githubusercontent.com/8141931/73359131-d133e700-42a8-11ea-8235-13617f782816.png">

as a result:

<img width="176" alt="Screenshot 2020-01-29 at 15 10 35" src="https://user-images.githubusercontent.com/8141931/73359464-91b9ca80-42a9-11ea-84f6-465e7becb3af.png">

<img width="400" alt="Screenshot 2020-01-29 at 15 11 12" src="https://user-images.githubusercontent.com/8141931/73359481-9b433280-42a9-11ea-81ab-39491108a337.png">

**Comment by muccy** [comment]
So the trick was to add bannerView in view hierarchy before to invoke `findPrebidCreativeSize`.
Now I have another problem: I refreshed banner 20 times or more, but I only get _The HTML doesn't contain a size object_

**Comment by yoalex5** [comment]
Add a Charles log, please

**Comment by muccy** [comment]
I'm using test project I shared.

Xcode output:
```
2020-01-29 03:13:10034 [ℹ️][RequestBuilder.swift]:58 22 buildRequest(adUnit:) -> Prebid Request post body [AnyHashable("ext"): ["prebid": ["cache": [AnyHashable("bids"): [:]], "targeting": [:], "storedrequest": [AnyHashable("id"): Optional("bfa84af2-bd16-4d35-96ad-31c6bb888df0")]]], AnyHashable("device"): [AnyHashable("devtime"): 1580307190, AnyHashable("os"): "iOS", AnyHashable("pxratio"): 2.0, AnyHashable("w"): 414.0, AnyHashable("lmt"): 0, AnyHashable("h"): 896.0, AnyHashable("model"): "Simulator", AnyHashable("connectiontype"): 1, AnyHashable("osv"): "13.3", AnyHashable("ua"): "Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148", AnyHashable("make"): "Apple"], AnyHashable("imp"): [[AnyHashable("ext"): [AnyHashable("prebid"): [AnyHashable("storedrequest"): [AnyHashable("id"): "6ace8c7d-88c0-4623-8117-75bc3f0a2e45"]]], AnyHashable("banner"): [AnyHashable("format"): [[AnyHashable("h"): 250.0, AnyHashable("w"): 300.0]]], AnyHashable("id"): "F2136C14-F90C-4943-9F1B-ABFD61521A11", AnyHashable("secure"): 1]], AnyHashable("source"): [AnyHashable("tid"): "395EE3A2-D413-4052-AE1D-16EABFE11C3A"], AnyHashable("id"): "F0FE1877-50A2-4CE1-A1FC-CC44DAAF1CB4", AnyHashable("app"): [AnyHashable("ext"): [AnyHashable("prebid"): [AnyHashable("source"): Optional("prebid-mobile"), AnyHashable("version"): Optional("1.3.0")]], AnyHashable("publisher"): [AnyHashable("id"): bfa84af2-bd16-4d35-96ad-31c6bb888df0], AnyHashable("ver"): "1.0", AnyHashable("bundle"): "it.tcc.tmw"], AnyHashable("user"): [AnyHashable("gender"): "O"]]
2020-01-29 03:13:11101 [⚠️][AdViewUtils.swift]:51 24 warnAndTriggerFailure(_:failure:) -> The HTML doesn't contain a size object
```

Charles Log File:
[NoHTMLSize.chls.zip](https://github.com/prebid/prebid-mobile-ios/files/4128455/NoHTMLSize.chls.zip)

Thank you, bye

**Comment by yoalex5** [comment]
You receive `The HTML doesn't contain a size object` because `AdManager` returns creative without `hb_*` key.

Please check your AdManager setup, maybe you have some limitations

**Comment by muccy** [comment]
I'll enquire with my team, thank you

**Comment by muccy** [comment]
Ok, my team has explained me about `kb:*`. It's all ok.
Thank you again for support

**Comment by StarWindMoonCloud** [comment]
Hi @muccy @yoalex5 , how did you solve the problem? 
I encountered the same issue ("The HTML doesn't contain a size object"), but could not find out what's wrong
