### ISSUE TITLE
Issues with implementing the sdk

### ISSUE THREAD

**Issue by orim55353** [prebid/prebid-mobile-ios#266]
Hello everyone, im new to prebid, ive started working with it right now, and i think that the docs and the code are not on the same version.

I saw that the function thats supposed to run the prebid server is not available anymore on the new sdk,  any help with that?

**Comment by bszekely1** [comment]
HI @orim55353, can you please provide an example? Your comment is quite vague. The documentation should be written according to the most recent code. If there is a discrepancy please let us know the specifics.

Bryan

**Comment by orim55353** [comment]
Sure sorry about that, for example the function FetchDemand on AdUnit isnt available anymore, another examples are this 2 lines: 
Prebid.shared.prebidServerAccountId = @"YOUR_ACCOUNT_ID";
Prebid.shared.prebidServerHost = PrebidHostAppnexus;

they are not available on the sdk im running.

**Comment by bszekely1** [comment]
You can find a working example in the Demo App of the SDK package called "PrebidDemoSwift". Look at the file called AppDelegate.swift.

**Comment by orim55353** [comment]
I looked at it, its using the lines that are not available in my sdk, my sdk provides this way to initialize the sdk: 
        PrebidMobile.register([], withAccountId: "", with: .appNexus, andPrimaryAdServer: .DFP)

**Comment by yoalex5** [comment]
Hello @orim55353,

It seems that you use the 0.x version of Prebid SDK, the latest version is 1.4

**Comment by orim55353** [comment]
Thx @yoalex5 
can you send me the pod name to install the updated version?

**Comment by yoalex5** [comment]
Please use the next [syntax](https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions) to update Prebid version 

to get the latest version:
```
pod 'PrebidMobile'
```

to get a specific version:
```
pod 'PrebidMobile', '1.4'
```

**Comment by orim55353** [comment]
im getting this error:
[!] CocoaPods could not find compatible versions for pod "PrebidMobile":
  In Podfile:
    PrebidMobile (= 1.4)

None of your spec sources contain a spec satisfying the dependency: `PrebidMobile (= 1.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by yoalex5** [comment]
@orim55353, thanks for feedback

Try to use `1.3` (I checked it)
```
pod 'PrebidMobile', '1.3'
```

When `1.4` is ready I will notify you

**Comment by orim55353** [comment]
great thank you

**Comment by yoalex5** [comment]
Track an issue #267

**Comment by yoalex5** [comment]
@orim55353, [`Prebid v1.4` is in CocoaPods](https://cocoapods.org/pods/PrebidMobile)
