### ISSUE TITLE
As per New Guidelines Updating Apps that Use Web Views

### ISSUE THREAD

**Issue by Rajeswarinewscorp** [prebid/prebid-mobile-ios#268]
Hello Team,

We have Integrated Branch SdK in our App. As per the Latest Apple Review Guidelines Apps that Use UI Web Views should Updating to WKWebView. 

Is there any Upgradation is happening from your end. Or How it would be.

It will be great if we can get the confirmation On this.

**Comment by yoalex5** [comment]
Hello @Rajeswarinewscorp,

Could you please check issue #236 ?
