### ISSUE TITLE
Add more documentation around GDPR context

### ISSUE THREAD

**Issue by ignazioc** [prebid/prebid-mobile-ios#291]
## Type of issue
As I'm updating `prebid-mobile-ios` from `1.2` to `1.5`  I found a change on the public interface of the `Targeting` class.

```diff
- public var subjectToGDPR: Bool {
+ public var subjectToGDPR: Bool? {
```

The rest of the change introduced by this commit `04fd9407eb94f2d8b15ba011b6330cdc2ae6e1c6` (`Support for US Privacy flag (#256)`)  is unclear to me because I'm not familiar with the US Privacy rules.

In particular I don't get:
- Why this property allows to be set with `nil` 
- Why when set with `nil` returns a different value.

@yoalex5  Is the author of the commit, maybe can give more insight? 

Thanks.

## Description
If someone can explain better the differences between `StorageUtils.pbGdprConsent()` and  `StorageUtils.iabGdprConsent()` I'll add a PR with a Readme about the topic.

**Comment by yoalex5** [comment]
Hello @ignazioc 

1)
 > Why this property allows to be set with nil

`subjectToGDPR` according to [official doc](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Mobile%20In-App%20Consent%20APIs%20v1.0%20Final.md#cmp-internal-structure-defined-api-) has thee defined states: 

>IABConsent_SubjectToGDPR: String 1 - (subject to GDPR), 0 - (not subject to GDPR), Nil - undetermined (default before initialization)

2)
>Why when set with nil returns a different value.

>explain better the differences between StorageUtils.pbGdprConsent() and StorageUtils.iabGdprConsent()

When a publisher **set** `subjectToGDPR` the PrebidSDK write a change using internal key - `kPBGdprSubjectToConsent` key

When a publisher  **get** `subjectToGDPR` the PrebidSDK check internal value(using `pbGdprConsent()` - `kPBGdprSubjectToConsent` key), if not - check a shared value (using `iabGdprConsent()` - `IABConsent_SubjectToGDPR` key)

This technik allows PrebidSDK to provide and to use `subjectToGDPR` without changing a shared value (`IABConsent_SubjectToGDPR` key). 

3) As for `04fd9407eb94f2d8b15ba011b6330cdc2ae6e1c6 ` commit. It is my fault that I committed a bunch of changes as a single commit. This commit introduced `US Privacy flag` and bug fixes for `GDPR`. 

The  description contains: `3. subjectToGDPR can be assign to nil to get an iab value`.
Previous revision contained `public var subjectToGDPR: Bool` - `subjectToGDPR` is not optional and always is `true` or `false`. It produced a situation when a publisher set `pbGdprSubject`, `iabGdprSubject` is not used anymore

**Comment by yoalex5** [comment]
Hello @ignazioc 

Can I close this issue ?
