### ISSUE TITLE
Remove usage of UIWebView

### ISSUE THREAD

**Issue by ton-impalastudios** [prebid/prebid-mobile-ios#297]
**Is your feature request related to a problem? Please describe.**
Submitting an app with the usage of UIWebView will not be accepted in the near future

`ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).`

**Comment by yoalex5** [comment]
It will be fixed at v1.6
