### ISSUE TITLE
Make parameter for "test=1" value in request

### ISSUE THREAD

**Issue by DrMoriarty** [prebid/prebid-mobile-ios#299]
**Is your feature request related to a problem? Please describe.**
The prebid server can response more debug data when request contains test=1 parameter.

**Describe the solution you'd like**
But this library doesn't allow me to set up this parameter in any way.

**Describe alternatives you've considered**
Of course I can set test=1 in stored_imps or stored_request. But it isn't very comfortable to change server side parameters when I want to check output in application side.

**Additional context**

**Comment by yoalex5** [comment]
Also you can use [Charles Proxy](https://www.charlesproxy.com/) to set `"test" : 1`

**Comment by yoalex5** [comment]
We will be adding this into release 1.7. The description is documented here: prebid/prebid-mobile-ios#301
