### ISSUE TITLE
Build warnings (OS X 10.11.6, Xcode 8.0 [8A218a])

### ISSUE THREAD

**Issue by rmloveland** [prebid/prebid-mobile-ios#3]
These may just be due to not running the latest OS X and Xcode, so let me know if so!

The warnings are under *Target Integrity* and *Dependency Analysis*, and they're the same warning:

"iOS deployment target '10.2' for architecture 'x86_64' and variant 'normal' is greater than the maximum value '10.0.99' for the Simulator - iOS 10.0 SDK."

I got another warning about missing the IPA file, but I think that's because of #2 .

**Comment by nhedley** [comment]
I'm not sure why this is happening for you. Both of the deployment targets for the demo app and the framework are 8.0 on master. If you go to General -> Deployment Info -> Deployment Target, what do you see in that field?

**Comment by rmloveland** [comment]
Looks like:
- *Deployment Target*: 8.0
- *Devices*: Universal

(attached screenshot too in case that helps)

![screen shot 2017-08-01 at 4 59 23 pm](https://user-images.githubusercontent.com/1312291/28846808-d1f133a6-76da-11e7-8607-5e329a033d15.png)

**Comment by nhedley** [comment]
@rmloveland Are you still seeing ""iOS deployment target '10.2' for architecture 'x86_64' and variant 'normal' is greater than the maximum value '10.0.99' for the Simulator - iOS 10.0 SDK."" error even with that deployment info? I couldn't reproduce on my machine

**Comment by rmloveland** [comment]
Yes - after a **Product > Clean** too - although the example app is building and running, and showing ads in the simulator.

I'm fine to close unless you think it might portend anything more serious (not an engineer so IDK?).

**Comment by josecu** [comment]
@rmloveland Try lowering the deployment target of the PrebidMobileDemo project:

<img width="1400" alt="screen shot 2017-08-01 at 6 58 55 pm" src="https://user-images.githubusercontent.com/6942011/28850625-b95b7ff2-76eb-11e7-9aab-3ff8d8d38e44.png">

If you get a similar error after doing that but with "10.3" instead, lower the deployment target of the "PrebidMobile" project.

@nhedley The build version that @rmloveland provided is a big hint here - 8A218a is Xcode 8.0 which only comes with iOS 10.0. That is why Rich can replicate it while you cannot (I presume you’re running on the latest and greatest). Alternatively, @rmloveland, upgrade to OS X 10.12 & Xcode 8.3 and the issue will go away for you too!

**Comment by rmloveland** [comment]
Thanks, works for me.

**Comment by josecu** [comment]
https://media.giphy.com/media/iPTTjEt19igne/giphy.gif
