### ISSUE TITLE
iOS 14 Update

### ISSUE THREAD

**Issue by fprivitera** [prebid/prebid-mobile-ios#309]
**Is your feature request related to a problem? Please describe.**
No

as you may know, with iOS 14 you should ask permission to get the IDFA, this will affect the targeting capability, and probably you will not have any more an ID that is representing the user. Which also means the average eCPM. 

Are you thinking to introduce alternative IDs such as a prebid Device ID that can be used as a primary Id when IDfa is not available? 

thanks.

**Comment by bszekely1** [comment]
Hello @fprivitera, right now there is no current plan to make a prebid device ID. There are several proposals being discussed in the industry, however it is still too early to determine an official approach. Apple has not provided sufficient time to react, nor provide sufficient tooling to work within the confines of user opt outs for IDFA. One of the proposals on the table making some headway in IAB is to attempt to utilize the SKAdNetwork framework to allow at least the attribution component of advertising to live on post iOS 14.

**Comment by bszekely1** [comment]
Hi @fprivitera, After discussing with the community we will be moving forward with supporting the IAB proposal once it is final. We are not moving forward with creating our own scoped device ID.
