### ISSUE TITLE
Prebid SDK shouldn't set itself as the CLLocationManager's delegate.

### ISSUE THREAD

**Issue by AccuSBerejikian** [prebid/prebid-mobile-ios#310]
**Describe the bug**
The CLLocationManager's delegate is set to get the Location class in the PrebidSDK. 
However, our app needs to remain the delegate because we want to receive significant location updates.

**To Reproduce**
1. Install the SDK
2. Call fetchDemand(adObject:) on a BannerAdUnit instance.
3. Our app is no longer the delegate of the CLLocationManager.

**Expected behavior**
The CLLocationManager's delegate should not be overwritten.
I would suggest that the GPS coordinates be injected into the fetchDemand call if the caller wants to include it.
Another way might be thru swizzling magic (i'm not familiar at all with swizzling).

**Smartphone (please complete the following information):**
 - Device: iphone 11 Pro
 - OS: iOS 13.5.1

**Comment by bszekely1** [comment]
Hi @AccuSBerejikian, thanks for reporting the bug, we will be looking into the issue and follow up in the coming days.

**Comment by yoalex5** [comment]
Hello @AccuSBerejikian,

Today I checked a behavior of `CLLocationManager` and could not reproduce your issue.

I could register 2 delegates for every `CLLocationManager` instance. It seems that `CoreLocation` internally uses a list of `CLLocationManager` and `CLLocationManagerDelegate` and notifies each of them when receives a new location. 

I made tests using PrebidSDK v1.7 on simulator - iPhone 11 Pro Max v13.5 and a real device - iPhone 7 v13.4

Could you please check:
- Application's `CLLocationManager` is initialised in a main thread 
- Location refresh rate(`startMonitoringSignificantLocationChanges` or `startUpdatingLocation`)
- PrebidSDK's `func locationManager(_ manager:, didUpdateLocations locations:)` is called

Provide a specific details:
- version of Prebid SDK
- code snippets 

Thank you

**Comment by AccuSBerejikian** [comment]
You are right.  I noticed both delegates getting the callbacks.  I'm not sure why it wasn't working the first time around. Thanks for the help.
