### ISSUE TITLE
iOS 14 update planned?

### ISSUE THREAD

**Issue by craigomac** [prebid/prebid-mobile-ios#317]
**Is your feature request related to a problem? Please describe.**
Is any update planned during the next few weeks in anticipation of iOS 14 and the ATT framework? I presume that header bidding would continue functioning normally, since the user can already opt out of tracking via Limit Ad Tracking in the iOS Settings app, but for our peace of mind it's still good to know if any update to the iOS framework will be required for our first iOS 14-ready release.

**Comment by bszekely1** [comment]
Hi @craigomac, yes, Prebid SDK will provide support for the iOS 14 release soon. The IAB has still not released a final spec on support of iOS14. I will be drafting up a proposal in the next day or so as I gain more clarity on what to do. It's quite frustrating for sure not having clarity so close to the Apple release.

The piece on LMT is an open top that I pushed to have addressed in the IAB spec. The way I am reading the current spec is a new field will be introduced to express the user's opt in status for iOS users:


Attribute | Description | Type | Example
-- | -- | -- | --
atts | (iOS Only) An integer passed to represent the app's app tracking authorization status, where0 = not determined1 = restricted2 = denied3 = authorized | integer | "atts": 3

It will be up to the exchange / bid adapter to interpret how to use lmt on each attribute value. I welcome your feedback once I draft up the proposal.

**Comment by bszekely1** [comment]
We will use the other issue for this release that contains a better description.
