### ISSUE TITLE
Appnexus support for Rewarded Video

### ISSUE THREAD

**Issue by ppuviarasu** [prebid/prebid-mobile-ios#318]
Appnexus is planning to extend support for rewarded video demand.

The existing logic works fine but the parameter "is_rewarded_inventory" not supported on the server.

Modifying the ORTB request to not send this parameter if the demand server is appnexus would solve the issue

**Comment by bszekely1** [comment]
The is_rewarded_inventory flag is passed in as an extension to PBS. The AppNexus bid adapter can opt not to read this in PBS. How are you expecting other bid adapters who monetize in an AppNexus PBS integration? How would they know if the inventory is rewarded?

**Comment by ppuviarasu** [comment]
fixed the adaptor... Not an issue anymore
