### ISSUE TITLE
The new SDK fails to compile if compiled on XCode 11 or less

### ISSUE THREAD

**Issue by ppuviarasu** [prebid/prebid-mobile-ios#328]
The "AppTransparencyFramework" is part of XCode 12 & above 
If compiled on less versions of xcode, the compilation fails

Following failure on XCode 11.6

<img width="805" alt="Screen Shot 2020-10-06 at 4 58 49 PM" src="https://user-images.githubusercontent.com/19392402/95259551-55098000-07f5-11eb-94c1-37a04742bef9.png">
<img width="1034" alt="Screen Shot 2020-10-06 at 4 59 20 PM" src="https://user-images.githubusercontent.com/19392402/95259562-58047080-07f5-11eb-8688-0fd3e0003815.png">

**Comment by yoalex5** [comment]
Please update Xcode v12

**Comment by ppuviarasu** [comment]
Fixed with issue #1.8.2
