### ISSUE TITLE
Xamarin samples?

### ISSUE THREAD

**Issue by pboisso** [prebid/prebid-mobile-ios#33]

**Comment by pboisso** [comment]
Hi prebid dev team !

I see references to Xamarin in this repo but the source code does not seems to be in c# nor have nuget package available. 

I would be interested in doing some testing with prebid mobile with Xamarin. Would you have any guideline or sample to refer as a starting point?

Thanks and keep up the great work.

**Comment by nhedley** [comment]
Hi @pboisso,

We currently use Xamarin Test Cloud to run integration tests on the Prebid Mobile Demo app. The tests are written in Calabash and run on Xamarin Test Cloud devices through the Travis CI build. 

The actual Prebid Mobile SDK does not use Xamarin right now. Let me know if any additional information would be helpful! 

- Nicole

**Comment by pboisso** [comment]
Thanks @nhedley.  That's unfortunate, but I will sure keep an eye open for possible Xamarin support in the future.

**Comment by pboisso** [comment]
Hi Prebid Mobile team,

I'm wondering, one year later, if there is any intend to support Xamarin in the future?  This would open a lot of apps to use the SDK.

Thanks.

**Comment by pboisso** [comment]
Still nothing?
