### ISSUE TITLE
Instream Video - Tech Spec

### ISSUE THREAD

**Issue by ppuviarasu** [prebid/prebid-mobile-ios#332]
## Description
To expand on our video feature set in the Prebid SDK, we intend to add Instream video. Instream video will be builtin addition to the previous video release to integrate into Google IMA SDK. 

## Goals
Add instream support to allow publishers to send instream bids from demand servers to Google Ad server

## Proposed Design

Instream video will be a new ad unit sub-class of existing video ad unit:
- Instream video:
    - config ID
    - adUnit Size

The expectation is the publisher will leverage the [Google Interactive Media Ads render events](https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side#ima_client-side_overview) outside the Prebid SDK:

- IMAAdDisplayContainer: A container object where ads are rendered.
- IMAAdsLoader: An object that requests ads and handles events from ads request responses. 
- IMAAdsRequest: An object that defines an ads request. Ads requests specify the URL for the VAST ad tag, as well as additional parameters, such as ad dimensions.
- IMAAdsManager: An object that contains the response to the ads request, controls ad playback, and listens for ad events fired by the SDK.

<img width="843" alt="Screen Shot 2020-10-19 at 3 06 48 PM" src="https://user-images.githubusercontent.com/19392402/96500400-c9441a80-121c-11eb-8dfe-5fc417cf5b73.png">

### In-Scope
PrebidMobile will only support Google IMA SDK for the instream video. However we will provide API's that will provide the prebid keywords that a publisher can use to integrate with other adServer SDK's in future

### Out of Scope
MoPub - We will not be supporting as the adServer doesnt provide Video AdUnit

### Prebid SDK Changes
1. Create Instream Video AdUnit
2. Create 2 API's 
a. get the adServer object, fetch the demand & attach the keywords to the adServer Object
#### IOS
`dynamic public func fetchInstreamDemandForAdObject(adObject: AnyObject, completion: @escaping(_ result: ResultCode, _ adServerURL:String?) -> Void) `

b. fetch the demand & provide the keywords to the publisher to be used on any supported adserver objects
#### IOS
`dynamic public func fetchDemand(completion: @escaping(_ result: ResultCode, _ prebidKeys:[String : String]?) -> Void)`

### Google IMA SDK Params
https://support.google.com/admanager/table/9749596?visit_id=637390614911711317-3535938911&rd=2
The adTagURL needs to be constructed using the above specs
eg: ```https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&"
    + "iu=/19968336/Punnaghai_Instream_Video1&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&"
    + "output=vast&unviewed_position_start=1&"
    + "cust_params=sample_ct%3Dlinear%26hb_uuid%3D92badf76-d94b-46f4-8a70-8124ab4092cc```

The prebid keys are passed in the cust_params field

### Prebid Server OpenRTB Changes
None

### Prebid Server Changes
None

**Comment by bszekely1** [comment]
Will Prebid SDK hand off the Prebid bids to a video player who calls the ad server? Do you have a diagram how this will function?

**Comment by ppuviarasu** [comment]
The IMA sdk will take care of the rendering.

**Comment by bszekely1** [comment]
Thanks for the update Punnaghai. I would recommend this work with both fetchDemand where we pass the keys off the publisher or set the Ad Server targeting automatically. This is the case where the publisher uses the video player to call the ad server, they would need to pass the keys to the video player.

**Comment by bszekely1** [comment]
Additionally, would this be supported in the Mopub case?

**Comment by ppuviarasu** [comment]
> Thanks for the update Punnaghai. I would recommend this work with both fetchDemand where we pass the keys off the publisher or set the Ad Server targeting automatically. This is the case where the publisher uses the video player to call the ad server, they would need to pass the keys to the video player.

Yes we are providing 2 API's to support both cases. The tech spec has the implementation details for both

**Comment by ppuviarasu** [comment]
> Additionally, would this be supported in the Mopub case?

MoPub doesnt have video adUnit. they support only rewarded video
