### ISSUE TITLE
Location constantly being used

### ISSUE THREAD

**Issue by WesleyJacobsMP** [prebid/prebid-mobile-ios#336]
I've noticed that when `shareGeoLocation` is set to true, the locationManager is constantly polling for the location. 
I think this is a waste of energy in most cases and propose to look into a more granular approach.

For instance let developers choose to use `startMonitoringSignificantLocationChanges` instead, if that's all that's needed, or provide a callback to stop updating location when the first one is retrieved.

**Comment by bszekely1** [comment]
Hi @WesleyJacobsMP,

Yes, we have looked into this previously and decided then to table the problem. This would be a good time to revisit it. The Magnite team will develop a proposal solution for you and the community to review that gives the publisher options on the sensitivity to location that the device experiences.
