### ISSUE TITLE
Package.swift manifest

### ISSUE THREAD

**Issue by rochapablo** [prebid/prebid-mobile-ios#346]
**Is your feature request related to a problem? Please describe.**
Kind of. I'm trying to build an extension which it will use PrebidMobile as dependency. The problem is that I'm getting the following error `Pods/PrebidMobile has no Package.swift manifest`

**Describe the solution you'd like**
I just wanna be able to import Pods/PrebidMobile and use like the PrebidDemoSwift

**Comment by yoalex5** [comment]
Hello @rochapablo 

Are you working on [app extension](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/) ?

As for error it seems that Xcode is looking for `Package.swift` which is a part of `Swift Package Manager` which is now is  not supported by Prebid SDK

**Comment by rochapablo** [comment]
Hello @yoalex5 

No, it's more like a PrebidMobile extension that allow the developer use Prebid with a short setup.

I see, indeed it's `Swift Package Manager` that I'm trying to use.

Thanks anyway.

**Comment by bszekely1** [comment]
Hi @rochapablo, we plan on supporting Swift Package Manager at some point in early in 2021. No date defined yet. If you wish to contribute, feel free to let us know.

**Comment by rochapablo** [comment]
Hello, me again... do you have any idea what could I be doing wrong here (https://stackoverflow.com/questions/65904002/undefined-symbol-objc-class-when-creating-ios-framework)? 

Basically I'm trying to build a framework were Google-Mobile and PrebidMobile it's already installed as dependency.

**Comment by yoalex5** [comment]
Hello @rochapablo 

It seems that you have problems with linker. `DFPRequest` is a part of GAM SDK
It is hard to say more without details and source code
