### ISSUE TITLE
validateAndAttachKeywords doesn't account for change of DFPRequest to GAMRequest object

### ISSUE THREAD

**Issue by wvabrinskas** [prebid/prebid-mobile-ios#360]
**Describe the bug**
In `Utils.swift` in the function `validateAndAttachKeywords:` there's a bug with the check for the GAM SDK request object type. In version 8.1.0 of the `Google-Mobile-Ads-SDK` they changed the name of the `DFPRequest` object to `GAMRequest`. In the attached screenshot you can see that `.DFP_Object_Name` is described as `DFPRequest`. There should be an extra step to check for the new type `GAMRequest` here:

```
func validateAndAttachKeywords (adObject: AnyObject, bidResponse: BidResponse) {
        
        let adServerObject: String = String(describing: type(of: adObject))
        if (adServerObject == .DFP_Object_Name || adServerObject == .DFP_O_Object_Name ||
            adServerObject == .DFP_N_Object_Name || adServerObject == .GAD_N_Object_Name ||
            adServerObject == .GAD_Object_Name) {
```
Not adding this check results in custom parameters not being added to the `adObject` and thus the request object. 

**To Reproduce**
1. Make a prebid request with a GAMRequest object
2. Observe that no custom targeting parameters are added to the request even when there's a successful bid. 

**Expected behavior**
Custom parameters should be added to the `GAMRequest` 

**Screenshots**
![Screen Shot 2021-03-03 at 12 10 24 PM](https://user-images.githubusercontent.com/934347/109844148-db49b700-7c19-11eb-8e35-2372356516d9.png)

**Smartphone (please complete the following information):**
 - iPhone 12 Pro Max 
 - iOS 14.5 b3
 - PrebidMobile 1.10
 - Google-Mobile-Ads-SDK 8.1.0

**Comment by bszekely1** [comment]
I am assigning this to someone to look into however there are some breaking changes in Google Ad Manager version 8.x SDK that are being addressed in this PR: https://github.com/prebid/prebid-mobile-ios/issues/350

In the meantime, if you can look at that PR to see if resolves this condition, or just wait for Oleksandr to review it.

**Comment by wvabrinskas** [comment]
@bszekely1  it looks like that PR does contain a potential fix for this. Thank you

**Comment by wvabrinskas** [comment]
@bszekely1  i will close this for now as it appears PR #350 has fixed it
