### ISSUE TITLE
Optimization of SDK initialization

### ISSUE THREAD

**Issue by YuriyVelichkoOpenX** [prebid/prebid-mobile-ios#364]
**Describe the bug**

One of our publishers is experiencing crashes with Prebid SDK 1.9 on iOS 12. The part of the crash log is attached below.

**To Reproduce**

We haven't reproduced it. But looks like the initialization part of Prebid SDK can be improved and it could help to avoid the crash. 

**Expected behavior**

- Lightweight initialization
- No crashes

**Screenshots**

[PrebidSDKCrashLOG.txt.zip](https://github.com/prebid/prebid-mobile-ios/files/6123749/PrebidSDKCrashLOG.txt.zip)

**Additional context**

Prebid SDK creates a WKWebView and executes javascript inside the Prebid.init() to get the userAgent value. 

Let's consider the next optimisations here:

1.  Init RequestBuilder.UserAgent asynchronously 
2. Do not add webView to the view hierarchy of UIApplication.shared.keyWindow
3. Do not use DispatchGroup just call the callback on the DispatchQueue.main 

They should help to avoid a crash on adding the webview into the view hierarchy and will make the initialization of SDK a bit faster.

**Comment by avermaiOS** [comment]
Changes are done in this PR https://github.com/prebid/prebid-mobile-ios/pull/366
