### ISSUE TITLE
Bitcode issue

### ISSUE THREAD

**Issue by rakesthedon** [prebid/prebid-mobile-ios#365]
Hi!

**Describe the bug**
I'm encountering an issue when try to build my app using bundler and fastlane.

ld: bitcode bundle could not be generated because 'PATH_TO_MY_APP_FRAMEWORKS/Prebid/PrebidMobile.framework/PrebidMobile' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file 'PATH_TO_MY_APP_FRAMEWORKS/Prebid/PrebidMobile.framework/PrebidMobile' for architecture arm64

**Configuration**
xcode version: 12.4
targeted os: iOS 11.3
the framework was build with the `./scripts/buildPrebidMobile.sh` and embeded in the app
there is no issue when using cocoapod but that would disrupt my team workflow too much

**Comment by rakesthedon** [comment]
It's also failing when i try to archive my app with Xcode directly

**Comment by yoalex5** [comment]
Hello @rakesthedon 

I see that the problem in Bitcode, we do not specify any bitcode flags when building SDK(using buildPrebidMobile.sh). 
I setup a new app to play with bitcode and  Prebid SDK but could not reproduce this error.
Could you please more details how to simulate it?

**Comment by rakesthedon** [comment]
Hi! try to create an archive with the sdk when it's build with the script and not with cocoapod

**Comment by yoalex5** [comment]
I see

Full error code
```
ld: bitcode bundle could not be generated because '<path_to_prebidmobile>' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '<path_to_prebidmobile>' for architecture arm64
```

**Comment by yoalex5** [comment]
Hello @rakesthedon 

I have created PR #371. It should fix problem with bitcode
Could you please check it ?
