### ISSUE TITLE
Rearchitect multi module structure

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#368]
**History:**
First iteration was implemented in #239

![PrebidMobile module v2](https://user-images.githubusercontent.com/8141931/115599110-df25bb80-a2e3-11eb-8b97-598d62e26741.png)

**Current situation:**
We have two targets(PrebidMobile and PrebidMobileCore) which use the same product name and module name(PrebidMobile). At the moment these two modules are the same, they include the same source files. We considered PrebidMobile as a full SDK

Usage:
```
import PrebidMobile
```

Advantages:
- `import PrebidMobile` is used for all products

Disadvantages:
- every source  file should be manually added in every target where it is used, as a result it simple to miss some file or add unnecessary file. It is hard to find this mistake
- hard to support new modules. When new module is creating you should add necessary files(at least from Core module) manually
- is not supported by Carthage(we use custom script as a workaround #277)
- is not supported by SPM

**Proposition:**

1. Use more native approach
2. Set a unique product name and module name for each product:
    - PrebidMobile instead of PrebidMobileCore. It will allows us to seamless migration because it doesn't cause breaking changes. All publishers which now use `PrebidMobileCore` or `PrebidMobile` don't need to replace module names in source files
    - PrebidMobileFull instead of PrebidMobile. PrebidMobileFull will not include any source files it will be just a name of dependency which will be responsible to add all sub-dependencies 

3. Set dependencies between them
4. Edit final distribution binaries(FatFramework, CocoaPods, Carthage, SPM, cross-project dependency)

Usage:
```
import PrebidMobile
import PrebidMobileRendering
```

@bszekely1 , @YuriyVelichkoOpenX what do you think ?

**Comment by YuriyVelichkoOpenX** [comment]
I totally support the proposed approach. Each module should consist unique set of files and have dependencies on other modules if needed. 

I would like to suggest to review the structure of the Smaatto SDK and use the same approach:
https://developers.smaato.com/publishers/nextgen-sdk-ios-integration/

OpenWrap has the similar one in the scope of event handlers:
https://community.pubmatic.com/display/IDFP

So in the result I would like to see such dependencies tree:

PrebidMobile (includes all ad formats except event handlers)
PrebidMobileBanner
PrebidMobileInterstitial
PrebidMobileNative
PrebidMobileInstream
.....

PrebidMobileEventHandlerGAM
PrebidMobileEventHandlerMoPub

Under the hood PrebidMobile*  modules will have dependencies to PrebidMobileRendering, PrebidMobileCore, and PrebidMobileTargeting, which will be independent frameworks with their distinct functions.

Publishers may include a particular module or all of them at once by using PrebidMobile which will include all formats. I think we can avoid using of PrebidMobileFull in this case. 

For now, we can start with the modules proposed in this ticket.

**Comment by yoalex5** [comment]
Hello @YuriyVelichkoOpenX 

>So in the result I would like to see such dependencies tree:
PrebidMobile (includes all ad formats except event handlers)
PrebidMobileBanner
PrebidMobileInterstitial
PrebidMobileNative
PrebidMobileInstream

I am not sure that we should split Prebid SDK on so many modules because there are not a lot of unique classes for each of them. 

>Under the hood PrebidMobile* modules will have dependencies to PrebidMobileRendering, PrebidMobileCore, and PrebidMobileTargeting, which will be independent frameworks with their distinct functions.

I don't think that we should create a standalone PrebidMobileTargeting module

>Publishers may include a particular module or all of them at once by using PrebidMobile which will include all formats. I think we can avoid using of PrebidMobileFull in this case.

Yes, you are right and it is a good approach. But I have proposed `PrebidMobileFull` to avoid breaking changes with current implementation and so that publishers could have a seamless migration to new version 

My vision is
```
//breaking changes
PrebidMobileCore <- PrebidMobileRendering <- PrebidMobile

//no breaking changes(from current perspective)
PrebidMobile <- PrebidMobileRendering <- PrebidMobileFull
```

**Comment by YuriyVelichkoOpenX** [comment]
Hey @yoalex5,

> I am not sure that we should split Prebid SDK on so many modules because there are not a lot of unique classes for each of them.

Right, it is a long-term question and we can discuss certain pros and cons later when rendering became an essential part of SDK. After that, we will clearly see the structure of API and related classes. So we will be able to say whether it worth having such precise modularisation or not. It looks good from the publisher's perspective since gives a precise understanding of used features but, indeed, the internal differences in the modules are minimal. 

>  PrebidMobileTargeting

For sure! Probably it is redundant. This module appeared in my mind in terms of [this](https://github.com/prebid/prebid-mobile-ios/issues/363#issuecomment-801074899) modularization roadmap as the transitional common item. But it will be better if we keep the targeting functionality inside another (maybe PrebidMobileFull) module.

> PrebidMobileFull

Got it. I missed the point that publishers can already use PrebidMobileCore as a dependency name. In any case, I'd try to find a more accurate name based on the module's purpose, f.e. PrebidMobileBidding or PrebidMobileRequester. Or even PrebidMobileKernel.
