### ISSUE TITLE
Support AdMob 

### ISSUE THREAD

**Issue by YuriyVelichkoOpenX** [prebid/prebid-mobile-ios#380]
# Motivation

Publishers who already use AdMob for monetization may want to increase their revenue using Prebid.

For instance, BidMachine already provides [AdMob Integration ](https://doc.bidmachine.io/eng/ssp-publisher-integration-documentation/checklist-integration-testing-guide/bidmachine-ios-sdk-integration#BidMachineiOSSDKIntegration-AdMobExample) for their publishers. 

> Note: This is not an "intent to implement" feature request but rather a description of a helpful feature that could be implemented if the community agrees with its value or if some real feature request will appear from the publisher or other members. 

# Prerequisites 

The rendering module. 

# Description

Firstly publisher should create a Mediation Group with Custom Events on AdMob.

1. For each ad source set the rendering adapter, f.e. `PrebidAdMobBannerCustomEvent`
1. For each ad source set the bid price in the Property string, f.e. `{pb_hb:1.00}`
1. Set the appropriate price for the ad source, the same as for the Property string, f.e. `$1.00`

Further, the Prebid SDK will work as a mediated SDK inside the AdMob monetization solution.

1. Prebid SDK makes a bid request and caches the winning bid.    
1. GMA SDK makes an ad request (without any targeting keywords because AdMob doesn't support them)
1. In the scope of the received ad response, GMA SDK instantiates the prebid adapter and passes the ad source properties into it
    1. The prebid adapter searches the bid in the prebid SDK's cache by given ad source's properties 
    1. If the cache contains the bid with the same keywords as the ad source's properties - it will be shown
    1. If there is no bid with given properties the adapter will fail the chain step
1. The process is running until some ad source wins. 

# Peculiarities
    
It works like targeting of ad sources but on the client side inside the AdMob waterfall. 

**It doesn't look like In-App bidding but still helps publishers to increase their revenue using prebid.** And for such publishers, it may serve as the first step for moving to the pure In-App bidding integration.

**Comment by bszekely1** [comment]
This would be one step forward and two steps back for header bidding. The approach here would stymie the movement of header bidding with the regression of integrating into the waterfall. All this would do is help Google in their quest to move mobile traffic away from GAM and over to AdMob. AdMob does not and will not have the advanced header bidding feature set available. We should discourage such integration. I don't feel this would be a good first step for a pub to migrate since changing ad server's is difficult. We will only make it more comfortable for them to stay.

**Comment by maddapper** [comment]
Yes, I'll have to agree with Bryan here as far as a Prebid Mobile AdMob adapter goes.  That said, outside of anything AdMob related, a rendering module does sound like an interesting idea since it would mean we wouldn't need to be tied into either AdMob, GAM, or MoPub for that matter.

**Comment by YuriyVelichkoOpenX** [comment]
Just to be clear - I totally understand that the integration into any of the waterfall engines distorts the In-Ap Bidding approach.

However, I want to understand the prebid strategy in the case when the publisher has, for example, an Ad-Mob integration, and wants to add 2 or 3 prebid bidders. These bidders give 5% filtrate for publisher’s inventory. And CPM for these bidders is not bigger than other networks CPMs. But it is ok for the publisher because he still can improve his revenue by filling some gaps in the fill rate of current ad sources. Let's assume that some ad sources does not have prebid adapters.

How should the publisher act in this case? 
- abandon from prebid since the community do not gives a way to integrate demand to his current monetization solution, and integrate the same demand using abilities of certain platform (mediation)
- build a complex integration on the client side in order to manage prebid and non-prebid demand. It is possible but hardly achievable since publishers do not like to build complex custom monetization frameworks. Most likely they will just integrate demand partners via mediation and forget about prebid opportunities. But this is not what we want  :)

Also need to keep in mind that for publisher there is no sense to prioritize the prebid demand over mediation demand if some ad network could give an ad with higher CPM. It is actual for any primary server.

So I would not be so categorical so far. As I know there are demand sources that do not support prebid, but publishers still want to integrate them alongside prebid to compete over the same inventory. For now it is possible only with mediation/waterfall engines (AdMob, GAM, MoPub).

Until the publisher can integrate all his demand via prebid and this demand doesn’t give about 90% fillrate we should assume that in the most cases prebid will be used as any other ad source on some server or mediation platform. 

As soon as publishers get the ability to integrate all their demand partners via prebid, including TAM, the need in any other server will go away. Publishers will earn only with prebid auction.

Also, I think that no one will switch from waterfall server to prebid in one step without testing the actual difference. Publishers would rather stay with the current monetization solution. And the best way to push publishers to prebid it is to allow prebid demand to compete with other ad sources and show its actual performance. It will encourage publishers to migrate to prebid.

**Comment by bszekely1** [comment]
if Google pushes pubs to use AdMob instead of Google Ad Manager, this would help reinforce this move. We have several items to work on for the ad rendering ahead of us, let us not focus too much energy on this topic to distract from the current implementation. We have spoken about it previously, two years ago and decided not to go down that route of acting as an ad network in the waterfall. I will ping the group again on the topic but the overall consensus was while it could bring more money short term it would hurt the product overall and would be a challenge to remove once the integration was complete. People don't switch ad servers very easily / quickly.

**Comment by YuriyVelichkoOpenX** [comment]
Right, sounds good!

And it looks reasonable to migrate publishers from AdMob to GAM+Prebid transferring their ad sources in waterfall to the demand partners on prebid.

**Comment by YuriyVelichkoPI** [comment]
@mittal-ank, @mmullin here is an issue with the description of the AdMob integration flow.

**Comment by YuriyVelichkoPI** [comment]
Hi @mittal-ank @mmullin

Here is an example of the ad response for AdMob

[AdMobAdRequest.txt](https://github.com/prebid/prebid-mobile-ios/files/7693892/AdMobAdRequest.txt)


it contains about 20 items from the respective mediation group. So it looks like we can support integration with AdMob with minimal latency.
