### ISSUE TITLE
Bidder

### ISSUE THREAD

**Issue by annaadv7** [prebid/prebid-mobile-ios#383]
Hi,

We would like to implement the adaptor in java(instead of Go) as per the specs that are in https://docs.prebid.org/prebid-server/developers/add-new-bidder-java.html. Could you please confirm that this adaptor(developed in java) will work with all the supply partners?

If we need to implement an additional part (except for the details of https://docs.prebid.org/prebid-server/developers/add-new-bidder-java.html), could you please share with me the link to the specs?

Thanks,

**Comment by bszekely1** [comment]
You don't need to create an issue ticket to write an adapter, you can simply write one and submit a PR to the Prebid Server repository: https://github.com/prebid/prebid-server-java

The link you provided should be all you need. If you have issues, you can post an issue in that repo.
