### ISSUE TITLE
Introduce a special repository for testing podspec files

### ISSUE THREAD

**Issue by VadimKhohlovOpenX** [prebid/prebid-mobile-ios#392]
## Motivation

The Cocoapods documentation [recommends](https://guides.cocoapods.org/making/making-a-cocoapod.html) to test podspec files before pushing its to Trun: "Before releasing your new Pod to the world its best to test that you can install your pod successfully into an Xcode project."

One of the way to do it is usage of a private repository for podspecs:
`pod 'NAME', :git => 'https://example.com/URL/to/repo/NAME.git'`

Here is a repository which is used by the Apollo SDK: https://github.com/openx/mobile-ios-sdk-test-podspec

## Implementation Proposal

We need a special repository in https://github.com/prebid 
In this case it is possible to create scripts for automatic testing podspec files before pushing it to Cocapod Trunk.

**Comment by YuriyVelichkoPI** [comment]
https://github.com/prebid/mobile-ios-sdk-test-podspec
