### ISSUE TITLE
It crashes

### ISSUE THREAD

**Issue by ton-impalastudios** [prebid/prebid-mobile-ios#44]
[Crashes PrebidMobile.pdf](https://github.com/prebid/prebid-mobile-ios/files/1391330/Crashes.PrebidMobile.pdf)

**Comment by nhedley** [comment]
Hi @ton-impalastudios,

Thanks for reporting. Can you confirm which version of Prebid Mobile you are using? 

Best,
Nicole

**Comment by ton-impalastudios** [comment]
0.0.3

**Comment by nhedley** [comment]
@ton-impalastudios This crash was fixed in 0.0.4. If you upgrade to the latest version 0.1.1 you should no longer see this crash.
