### ISSUE TITLE
Need fix:  Video Rewarded MoPub

### ISSUE THREAD

**Issue by MaksPetrukhnoPI** [prebid/prebid-mobile-ios#443]
**Bug**
When redirecting back to video rewarded ad page appropriate delegates are not called and after redirecting to search page and again to ad page a show button doesn't display anything 

**To Reproduce**
1. Search for Video Rewarded 320x480 (MoPub)
2. Navigate to ad page
3. Click show button
4. Wait till ad ends
5. Click on ad
6. Navigate back to search page
7. Navigate again to ad page
8. Click on Show
9. See that ad is not displayed and show button is not enabled 

**Expected behavior**
1) After redirecting back to ad page, appropriate delegates should be called
2) After redirecting back to search page and then again to ad page, show button should display ad

**Screenshots**
![simulator_screenshot_8E62551E-7778-4E45-97BE-9A05ADD849F2](https://user-images.githubusercontent.com/94057303/142405823-ad0cef80-435d-4f57-b044-88fb9ae33425.png)

![simulator_screenshot_FEBDBD29-6285-4FEC-95FE-C536D876358D](https://user-images.githubusercontent.com/94057303/142405852-ad79d098-5a20-4798-bd18-d99fd5df74ee.png)

**Smartphone:**
 - Device: Iphone 8
 - OS: iOS 14

**Comment by MaksPetrukhnoPI** [comment]
rewardedVideoAdShouldReward called is not enabled

**Comment by YuriyVelichkoPI** [comment]
The issue will be addressed in the scope of #450.
