### ISSUE TITLE
Need fix: Display Interstitial 320x480 (MoPub) 

### ISSUE THREAD

**Issue by MaksPetrukhnoPI** [prebid/prebid-mobile-ios#445]
**Bug**
After redirecting back to ad page, interstitial ad is not displayed and appropriate delegates are not called 
**To Reproduce**
1. Search for Display Interstitial 320x480 (MoPub) 
2. Turn on mock server
3. Navigate to ad page
4. Click show button
5. Click on ad
6. Click close button
7. See that interstitial ad is not displayed and delegates are not called

**Expected behavior**
After redirecting back to ad page, interstitial ad should be displayed and appropriate delegates should be called

**Screenshots**
![simulator_screenshot_AE933887-80A7-451B-B82B-26F083A2F596](https://user-images.githubusercontent.com/94057303/142417141-6a4111e1-f6c0-4b13-a4cb-97c63e6319e3.png)

**Smartphone:**
 - Device: iPhone 8
 - OS: iOS 14.0

**Comment by MaksPetrukhnoPI** [comment]
Delegates are not called

**Comment by YuriyVelichkoPI** [comment]
@MaksPetrukhnoPI, the fix has been merged. Please verify it.
