### ISSUE TITLE
Rewarded Adapter - rewardedAdShouldReward is not called for the ads with End Card

### ISSUE THREAD

**Issue by OlenaPostindustria** [prebid/prebid-mobile-ios#450]
## Description

For the ad with companion creative, the delegate method `rewardedAdShouldReward` is not called due to the intricate flow of delegate calls. 

The start point for investigation should be a `FIXME` comment in `modalManagerDidFinishPop` method in the `PBMHTMLCreative`.  

## Objective

Refine the flow of the ad state signaling (delegate calls) in order to make it more convenient and fix the current behavior.

**Comment by YuriyVelichkoPI** [comment]
MoPub is not relevant anymore
