### ISSUE TITLE
Support openRTB app.name field in the Bid Request

### ISSUE THREAD

**Issue by hdeodhar** [prebid/prebid-mobile-ios#489]
**Describe the solution you'd like**
Add support for app.name field in the [openrtbApp](https://github.com/prebid/prebid-mobile-ios/blob/master/PrebidMobile/RequestBuilder.swift#L267) function. 

**Additional context**
At least one bidder is not able to bid on iOS app requests if app.name field is not present.

**Comment by YuriyVelichkoPI** [comment]
The changes should be applied to both the original API and rendering API
