### ISSUE TITLE
Support for Seller-Defined Audiences for First Party Data

### ISSUE THREAD

**Issue by CJxD** [prebid/prebid-mobile-ios#515]
Issue #461 describes a plugin mechanism that can add any data to an ORTB bid request, and is intended to support Seller-Defined Audiences as defined by the [IAB Data Transparency Standards](https://iabtechlab.com/wp-content/uploads/2021/03/IABTechLab_Taxonomy_and_Data_Transparency_Standards_to_Support_Seller-defined_Audience_and_Context_Signaling_2021-03.pdf) and [Prebid's FPD documentation](https://docs.prebid.org/features/firstPartyData.html#segments-and-taxonomy).

There [exists today several methods](https://docs.prebid.org/prebid-mobile/pbm-api/ios/pbm-targeting-ios.html) to add data to certain fields of the bid request, such as:

`Targeting.shared.addUserData(key: "globalUserDataKey1", value: "globalUserDataValue1")`

However, this seems to be limited to adding Strings only.

To support SDA, there needs to be a way of adding Objects to the user (`user.data`) and context (`content.data`) sections of the ORTB object, which looks like this:

```
{
  "user": {
    "data": [
      {
        "name": "www.dataprovider1.com",
        "ext": {
          "taxonomyname": "proprietary taxonomy abc"
        },
        "segment": [
          {
            "id": "687"
          },
          {
            "id": "123"
          }
        ]
      },
      {
        "name": "www.dataprovider1.com",
        "ext": {
          "taxonomyname": "IAB Audience Taxonomy 1.1"
        },
        "segment": [
          {
            "id": "687"
          },
          {
            "id": "123"
          }
        ]
      }
    ]
  }
}
```

**Comment by YuriyVelichkoPI** [comment]
It looks like an incorrect implementation on the prebid mobile side. We defiantly should support adding `data` objects, even instead of the key-value approach.

**Comment by YuriyVelichkoPI** [comment]
The changes should be applied to both original API and rendering API

**Comment by YuriyVelichkoPI** [comment]
Hi @CJxD! In the ticket you mentioned the `site` object, however, the SDK uses the `app` object. 

So I just want to clarify whether you request the presence of the `site` object? Or it was just a misprint?

**Comment by CJxD** [comment]
Hey @YuriyVelichkoPI! I misprinted: the context taxonomy in the SDA spec relates to the `content.data`  rather than `site.content.data`. So essentially the `app` and `content` objects.

**Comment by YuriyVelichkoPI** [comment]
@CJxD one more question. The `content.data` looks like a dynamic object for each ad unit and ad request, isn't it? So the publisher should set it for each bid request, right?

**Comment by CJxD** [comment]
> @CJxD one more question. The `content.data` looks like a dynamic object for each ad unit and ad request, isn't it? So the publisher should set it for each bid request, right?

Sorry I missed this! Yes, I think you're right
