### ISSUE TITLE
Introduce 1.12.2 version with changes for the original codebase

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#533]
# Motivation

Several feature requests for the original API were implemented, during the development of _1.14-beta_. They are needed for the current users of the original API so we should release them.

# Objectives

- Prepare the new branch `release-1.12` from the tag `1.12.1`
- Prepare the new branch `release-1.12.2` from the branch `release-1.12`
- Introduce the next changes in `release-1.12.2` (do not squash them on the release branch)
  - #468 
  - #490
  - #528 
  - #526 
  - #527
  - #531
  - #532 
  - #515
- Update the SDK version to `1.12.2`
- Prepare the podspec for release.

**Comment by OlenaPostindustria** [comment]
#### Result of running PrebidMobileTests 
<img width="328" alt="image" src="https://user-images.githubusercontent.com/92721590/155977778-5a361bb1-19f1-4315-b415-5c123fa1088b.png">
