### ISSUE TITLE
Release 1.14.0-beta1

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#546]
## Objective 

Follow the [release guide](https://docs.google.com/document/d/1VT1zUoKw_v4eXr0WI1ar_yXGJn2rrCd9MNE8ol-HcCM/edit#heading=h.eezs31y83s63) and create the `1.14.0-beta1` version.

**Comment by OlenaPostindustria** [comment]
### Result of InternalTestAppUITests
<img width="475" alt="Screenshot 2022-02-25 at 12 57 19" src="https://user-images.githubusercontent.com/92721590/155703856-134fb35d-e4fc-4b65-b854-f92703a72048.png">
