### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by laurenheinrichs** [prebid/prebid-mobile-ios#56]
I was receiving a server error which read: `Invalid request format: request.imp[0].ext contains unknown bidder: districtm. Did you forget an alias in request.ext.prebid.aliases?`

In order to get around this error, I had to manually go into PBServerRequestBuilder.m and uncomment the section //to be used when openRTB doesnt support storedRequests and comment out the section where it does support requests. This occurs in the method `- (NSArray *)openrtbImpsFromAdUnits:(NSArray<PBAdUnit *> *)adUnits withSecureSettings:(BOOL) isSecure`

please help make this easier and not so hack-y

**Comment by ppuviarasu** [comment]
Can you post the request that you are sending? This block is commented because we should not sending the placements direct & only the stored config id

**Comment by ppuviarasu** [comment]
Is this still an issue? can we close this?

**Comment by ppuviarasu** [comment]
Is this still an issue? Can we close this ?

**Comment by anwzhang** [comment]
@laurenheinrichs It seems like something's wrong with your config id setup in the prebid server UI, would mind sharing with us your config id to look at?
