### ISSUE TITLE
Problem with setting bid keywords on DFP Interstitial

### ISSUE THREAD

**Issue by ollirus** [prebid/prebid-mobile-ios#59]
I tried the demo app for DFP Interstitial. I succeed at registering ad units. But when I set bid keywords on ad object after  and call loadRequest, I had a persistent error.

`        [PrebidMobile setBidKeywordsOnAdObject:self.dfpInterstitial withAdUnitId:kAdUnit2Id withTimeout:600 completionHandler:^{
            [self.dfpInterstitial loadRequest:[DFPRequest request]];
        }];`

Then using DFP Troubleshoot, I found that request key values are always empty. So I resolved it by setting a custom targeting to DFPRequest:

`DFPRequest *request = [DFPRequest request];`
`PBAdUnit *__nullable adUnit = [[PBBidManager sharedInstance] adUnitByIdentifier:kAdUnit];`
`[request setCustomTargeting:[[PBBidManager sharedInstance] keywordsForWinningBidForAdUnit:adUnit]];`
`[self.dfpInterstitial loadRequest:request];`

According to the documentation I should use `setBidKeywordsOnAdObject` method for setting keywords. Could you explain what is my problem?

**Comment by ppuviarasu** [comment]
for DFP 
parameters are added under extras
so the call `keywordsPairs = [[PBBidManager sharedInstance] keywordsForWinningBidForAdUnit:adUnit];
                requestParameters = [[PBBidManager sharedInstance] addPrebidParameters:requestParameters withKeywords:keywordsPairs];`

addPreBidParameters adds it under extras keywords... not under keywords...
hope this helps

**Comment by dmitriyshashkin** [comment]
But why don't we see any keywords in DFP troubleshoot? If we send the custom targeting ourselves, we see keywords in troubleshoot.

**Comment by ppuviarasu** [comment]
Hi @dmitriyshashkin 

Sorry for the late response but the keywords are added only when the load request is called & the successive refresh request doesnt allow us to replace the keywords. Hence we have added under extras and replace for every refresh.

This is the current SDK design & works as is.

Thanks
