### ISSUE TITLE
MoPub Banner & Interstitial Ads Not Rendering Properly in iOS Demo

### ISSUE THREAD

**Issue by dianhua1560** [prebid/prebid-mobile-ios#60]
Downloaded the iOS Demo App.

Tried to render an ad from "MoPub + Banner" & "MoPub + Interstitial" combinations, but the ads are not displaying properly as using the DFP ad server:

- **MoPub Banner**, 
<img width="452" alt="screen shot 2018-03-22 at 5 21 33 pm" src="https://user-images.githubusercontent.com/10664425/37805156-9d03ae9e-2df5-11e8-8e6f-788b59e387d3.png">

- **MoPub Interstitial**, 
<img width="459" alt="screen shot 2018-03-22 at 5 22 11 pm" src="https://user-images.githubusercontent.com/10664425/37805166-a8d1d6e2-2df5-11e8-8625-aec74de886ac.png">

Whereas DFP ones are working as expected:
- **DFP Banner**, 
<img width="444" alt="screen shot 2018-03-22 at 5 23 29 pm" src="https://user-images.githubusercontent.com/10664425/37805184-ca9eb2f4-2df5-11e8-9e9f-1cc4074d9555.png">

- **DFP Interstitial**,
<img width="452" alt="screen shot 2018-03-22 at 5 23 41 pm" src="https://user-images.githubusercontent.com/10664425/37805185-d0bc8c38-2df5-11e8-9444-d8b8d0be8cbe.png">

**Comment by anwzhang** [comment]
Hi @dianhua1560, do you have the creative from the UIWebView for us to reproduce the issue? If you use safari's developer tool, should be easy to get it.

Thanks,
Wei

**Comment by dianhua1560** [comment]
Sure, below is the creative, and one thing i noticed is that sometimes it renders properly, and sometimes it doesn't ... like with a ratio around 2 out 5 times.

`ocument.write('\n<html>\n\n<head>\n<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"><\/script>\n\n<style>\nbody {\n\tposition: relative;\n\tpadding: 0;\n\tmargin: 0;\n\tfont-family: Tahoma, Geneva, sans-serif;\n\tfont-weight: 400;\n}\n#background {\n\tbackground-color: #ca5b3a;\n\twidth: 100%;\n\theight: 100%;\n\twidth: 300px;\n\theight: 0px;\n\tposition: fixed;\n\tz-index: -1;\n\topacity: 0;\n}\n\n#logo {\n    display: inline;\n\tposition: relative;\n\tleft: 110px;\n\ttop: 20px;\n\tcolor: #ca5b3a;\n\tbackground-color: white;\n\tpadding: 10px;\n\tpadding-top: 7px;\n\tpadding-bottom: 7px;\n\tfont-family: helvetica;\n\tborder-radius: 5px;\n\n\tfont-size: 15px;\n\n\tfont-weight: 300;\n}\n\n#title {\n\tposition: relative;\n\ttop: 50px;\n\tcolor: white;\n\tfont-size: 24px;\n\tfont-weight: bold;\n\topacity: 0;\n}\n#subtitle {\n\tposition: relative;\n\ttop: 50px;\n\tcolor: white;\n\tfont-size: 21px;\n\topacity: 0;\n}\n\n#btn {\n\tposition: relative;\n\ttop: 80px;\n\n\tborder: 1px white solid;\n\tpadding: 10px;\n\tborder-radius: 10px;\n\ttext-decoration: none;\n\tcolor: white;\n\tfont-family: Helvetica;\n\n\topacity: 0;\n}\n\n#btn:hover {\n\tcursor: hand;\n\tbackground-color: rgba(255,255,255,0.3)\n}\n\n</style>\n\n</head>\n\n<body>\n\n<div id=\"background\">\n\n\n</div>\n\n<div id=\"logo\">\n\tPrebid.js\n</div>\n\n<div id=\"title\">\n\tA Header Bidding Ad.\n</div>\n<div id=\"subtitle\">\n\tit\'s created in minutes.\n</div>\n\n<a id=\"btn\" href=\"http://prebid.org/getting-started.html\" target=\"_blank\">\n\tExplore How\n</a>\n\n<script>\n\nvar dur = 300;\n\n$(document).ready(function() {\n\t$(\"#background\").animate({\n\t\theight: 250,\n\t    opacity: 1\n\t  }, 200, function() {\n\n\t    $(\"#title\").animate({\n\t        opacity: 1,\n\t        left: \"+=27\"\n\t      }, dur, function() {\n\t    \t$(\"#subtitle\").animate({\n\t    \t    opacity: 1,\n\t    \t    left: \"+=55\"\n\t    \t  }, dur, function() {\n\t    \t    $(\"#btn\").animate({\n\t    \t        opacity: 1,\n\t    \t        left: \"+=90\"\n\t    \t      }, dur, function() {\n\t    \t        \n\t    \t      });   \n\t    \t  });    \n\t      });\n\t  });   \n})\n\n<\/script>\n\n</body>\n\n</html>');`

**Comment by dianhua1560** [comment]
any updates?

**Comment by ppuviarasu** [comment]
This is more of HTML rendering in webview... Did you try on a device?

**Comment by dianhua1560** [comment]
I tried in through simulator, not a real device.

How did that happen and why would it be different on a device? or were u asking me if I tried on a device or simulator?

**Comment by ppuviarasu** [comment]
Its mostly the network issue i am thinking... mopub is sending the ad over delay n the rendering might be a problem becuase of this... try on different simulators or devices & let me know... I will also try to reporduce the problem here... so far i haven't been successfull in reproducing the issue

**Comment by dianhua1560** [comment]
okay i will give it a try on a diff simulator.

BTW, the simulator that I had problem on is iPhone8 , 11.2

**Comment by ppuviarasu** [comment]
Closing this since we havent heard back... Assuming its closed
