### ISSUE TITLE
Some suspicious places may cause leak

### ISSUE THREAD

**Issue by vietta** [prebid/prebid-mobile-ios#617]
**Describe the bug**
In PrebidMobile SDK v1.12.2, I found some suspicious places in **BidManager.swift** that may cause a leak.

**line 41-44: callback is missing**
```
guard error == nil else {
    Log.debug("error calling GET on /todos/1")
    return
}
```

**line 47-51: callback should be called in the main thread and missing return**
```
if (data == nil ) {
    Log.debug("Error: did not receive data")
    callback(nil, ResultCode.prebidNetworkError)
}
```

**line 84: callback should be called in the main thread**
```
callback(nil, errorCode)
```

Can you review and provide a patch for improvement if needed?

**Comment by YuriyVelichkoPI** [comment]
I've closed this ticket since we no longer have the BidManager class.
