### ISSUE TITLE
Check backward compatibility with the stable release

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#622]
## Objectives

- Create a new test app and prepare it to test the integration of the original  API.
- Integrate Prebid SDK `v 1.12.2`
- Integrate GAM SDK
- Prepare test examples for the following ad formats:
  - display banner
  - display interstitial
  - video interstitial
  - native
 - Make sure that all cases work
 - Replace the Prebid SDK with the build from the master branch for version 2.0
 - Document and discuss all issues related to the replacement.
 - Apply fixes if needed
 - Make sure that all initial integration cases work 
 - Prepare the migration guide if needed

**Comment by OlenaPostindustria** [comment]
Link to repo with test app - https://github.com/OlenaPostindustria/PrebidDemo.
