### ISSUE TITLE
Can not build version 2.0.0 using Carthage

### ISSUE THREAD

**Issue by marcelklinek** [prebid/prebid-mobile-ios#631]
**Describe the bug**
Can not build `prebid-mobile-ios` version 2.0.0 using Carthage. Command gives errors posted below. Log is attached below as well.

**To Reproduce**
1. Create a `Cartfile` with following contents:

```
github "prebid/prebid-mobile-ios" ~> 2.0.0
```

2. Run `carthage update --use-xcframeworks --platform ios`

**Expected behavior**
Carthage builds `PrebidMobile.xcframework`

**Command output**

```
*** Fetching prebid-mobile-ios
*** Checking out prebid-mobile-ios at "2.0.0"
*** xcodebuild output can be found in /var/folders/c3/c18x0hqs01b1vzztbwvk908m0000gn/T/carthage-xcodebuild.LIBwOm.log
*** Building scheme "PrebidMobileGAMEventHandlers" in PrebidMobile.xcworkspace
Build Failed
    Task failed with exit code 65:
    /usr/bin/xcrun xcodebuild -workspace /Users/marcelklinek/Yieldlove/random-project/Carthage/Checkouts/prebid-mobile-ios/PrebidMobile.xcworkspace -scheme PrebidMobileGAMEventHandlers -configuration Release -derivedDataPath /Users/marcelklinek/Library/Caches/org.carthage.CarthageKit/DerivedData/13.3.1_13E500a/prebid-mobile-ios/2.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/c3/c18x0hqs01b1vzztbwvk908m0000gn/T/prebid-mobile-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/marcelklinek/Yieldlove/random-project/Carthage/Checkouts/prebid-mobile-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/c3/c18x0hqs01b1vzztbwvk908m0000gn/T/carthage-xcodebuild.LIBwOm.log
```
[carthage-xcodebuild.LIBwOm.log](https://github.com/prebid/prebid-mobile-ios/files/8631437/carthage-xcodebuild.LIBwOm.log)

**Comment by YuriyVelichkoPI** [comment]
Hi @marcelklinek ! Thanks for the report. We are working on this issue, but unfortunately, I can't give you ETA for the solution.

We have several problems here. The first one is Carthage's approach for building all schemas in the workspace. You see an error for GAM Event Handlers which, I believe, you don't even need. And this scheme requires a cocoapod dependency. So we have to reconsider the project structure and dependencies to support Carthage. 

The next problem is a dependency on Open Measurement SDK in the PrebidMobile. Which produces an error: 

![image](https://user-images.githubusercontent.com/21169695/167088509-56ae5fb6-6b56-4292-8203-8110790a2cf4.png)

So we have to contact IAB to figure out whether they support Carthage build or not. 

I'll keep you posted about the progress. 

Are you able to integrate PrebidMobile via cocoapods, or build it from source files?

**Comment by OlenaPostindustria** [comment]
Hi @marcelklinek!
You can use `2.0.0-carthage-prebid-mobile-only` tag to build `PrebidMobile.xcframework` with Carthage:
```
github "prebid/prebid-mobile-ios" == 2.0.0-carthage-prebid-mobile-only
```
Unfortunately, we still have issues with building `PrebidMobileAdMobAdapters, PrebidMobileGAMEventHandlers and PrebidMobileMAXAdapters` with Carthage, but we are working on resolving this problem.

**Comment by marcelklinek** [comment]
Hi @YuriyVelichkoPI and @OlenaPostindustria !

Thanks for support. `2.0.0-carthage-prebid-mobile-only` tag you provided works for us. We will use this workaround for now.
