### ISSUE TITLE
OMSDK Errors

### ISSUE THREAD

**Issue by GLStephen** [prebid/prebid-mobile-ios#639]
Are there instructions on how, or requirements, to get OMSDK to work with Prebid Mobile? We are receiving the below error and similar when trying to use Prebid mobile with AdMob. Any hel

At initialization:
```
prebid-mobile-sdk: 2022-05-11 12:56:08846 [‼️][PBMError.m]:68 +[PBMError createError:message:type:] -> Error Domain=org.prebid.mobile Code=0 "SDK internal error: Could not find omsdk script; it will not function" UserInfo={NSLocalizedDescription=SDK internal error: Could not find omsdk script; it will not function}
prebid-mobile-sdk: 2022-05-11 12:56:08849 [‼️][PBMOpenMeasurementWrapper.m]:306 -[PBMOpenMeasurementWrapper loadLocalJSLibWithBundle:] -> Could not load omsdk.js from file
prebid-mobile-sdk: 2022-05-11 12:56:08850 [ℹ️][Prebid.swift]:160 initializeSDK() -> prebid-mobile-sdk 2.0.0 Initialized
```

**Comment by YuriyVelichkoPI** [comment]
Hi @GLStephen! Thanks for the report.

It looks like a PrebidMobile issue. You shouldn't do anything to make it work. 

How do you integrate PrebidMobile? Using coocapods?

**Comment by YuriyVelichkoPI** [comment]
We'll fix the issue in the next release.

**Comment by GLStephen** [comment]
@YuriyVelichkoPI thanks for looking at it. I look forward to the update.
