### ISSUE TITLE
Prebid Mobile SDK 2.0.0 contains mixed language source files which let SwiftPM failing

### ISSUE THREAD

**Issue by ThomWee** [prebid/prebid-mobile-ios#640]
**Describe the bug**
I'm trying to update to PrebidMobile SDK 2.0.0 using SwiftPM. While updating from 1.12.0 to 2.0.0 the Xcode SwiftPM integration fails always.

**To Reproduce**
1. Open a project in Xcode where SDK version 1.12.0 with exact version target is used.
2. Update the SDK using 2.0.0 as dependency for this target
3. Check runtime log of Xcode while processing dependencies

**Expected behavior**
Like with SDK version 1.12.0 should also the 2.0.0 integration of the SDK work.

**Screenshots**
![image](https://user-images.githubusercontent.com/4629834/168073347-cf893ba7-992d-4b0c-9b84-53557550d490.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Xcode 13.3

**Comment by YuriyVelichkoPI** [comment]
Hi @ThomWee. Thanks for the report. 

Unfortunately, it is a known issue. The rendering code base has a lot of objective-c code. It doesn't allow to integrate PrebidMobile with SPM so far. The community and development team doesn't have the needed resources to rewrite the code to swift to fix the issue or modularize the SDK to work around it. So I can't give you an ETA for fixing this issue.

For now, we are going to rewrite the code gradually in the scope of other tasks. But the amount of work is pretty big.

**Comment by YuriyVelichkoPI** [comment]
Here is a related issue: #396

**Comment by bpkelsey** [comment]
Just curious, is there any update on this? Any closer to working with SPM?

**Comment by YuriyVelichkoPI** [comment]
Hi @bpkelsey ! No progress here. Prebid needs volunteers from the community to perform the migration.
