### ISSUE TITLE
SKAdNetwork support in v 2.0.0

### ISSUE THREAD

**Issue by marcelklinek** [prebid/prebid-mobile-ios#642]
Can’t make SKAdNetwork work in v 2.0.0.

Looks like support for SKAdNetwork was added in https://github.com/prebid/prebid-mobile-ios/pull/414

**To Reproduce**
1. Integrate `prebid-mobile-ios` v 2.0.0
2. Put a couple `SKAdNetworkIdentifier`s into Info.plist
3. Make a bid request

**Expected behavior**
PrebidMobile includes `SKAdNetworkIdentifier` in bid request

**Comment by OlenaPostindustria** [comment]
Hi @marcelklinek!

PrebidMobile also requires `sourceapp` property to include `skadn` object into bid request.
Have you set `Targeting.shared.sourceapp` property?

**Comment by marcelklinek** [comment]
Hi @OlenaPostindustria!

Thank you, after setting  `Targeting.shared.sourceapp property` it started working
