### ISSUE TITLE
Wanted to create custom SDK based on Prebid and Google Ad Manager

### ISSUE THREAD

**Issue by sagarbizspice** [prebid/prebid-mobile-ios#652]
## Type of issue

I wanted to create my own custom ios SDK/framework that will be dependent on prebid SDK and Google Ad manager SDK.

## Goals

If once the Prebid SDK and Google Ad Manager is added as dependency in my own library then one i build my own SDK/framework file it should contain both prebid library and google ad ,manager library as part of my own library. And when some other developer use that library they can have features of prebid sdk and google ad manager sdk and features of my SDK too.
This is not and issue but i need help on it whether it is possible or not. If it is possible then how it can be made possible please do guide me or help me tons of thanks in advance.

**Comment by YuriyVelichkoPI** [comment]
Hi @sagarbizspice!

Please, review projects for GAM Event handlers or AdMob adapters in the current repository. Both of these projects are dedicated to create frameworks that depend on PrebidMobile and GAM SDK. So it is similar to your needs and you can start with it. 

The same is relevant to the Android repository.

**Comment by YuriyVelichkoPI** [comment]
Hi @sagarbizspice! Sorry for the long silence. Is creating of custom SDK still relevant to you?
