### ISSUE TITLE
Pod install issue 

### ISSUE THREAD

**Issue by saudongctv** [prebid/prebid-mobile-ios#657]
**Describe the bug**
I got this issue when try to integration Prebid in my current project.
[!] Can't merge user_target_xcconfig for pod targets: ["PianoComposer", "PrebidMobile", "core"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

In pod file, I have:     
pod 'PianoComposer', '~> 2.4.0' 
    pod 'Firebase/Analytics'
    pod 'Firebase/Performance'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/InAppMessaging'

Could you help to check. Thank you

**Comment by OlenaPostindustria** [comment]
Hi, @saudongctv!

Please, try to use `2.0.1` PrebidMobile version to fix this issue.
