### ISSUE TITLE
Support for arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by frandelarosa** [prebid/prebid-mobile-ios#661]
I've added Prebid SDK 2.0 but can't compile the project because the arm64 simulator is not supported.

**Comment by OlenaPostindustria** [comment]
Hi, @frandelarosa! Thanks for the report. 

We had to remove arm64 because of our OM SDK, that didn't support this arch. 
Now we updated OM SDK to the latest version, that support arm64 and these changes will be available in the next release.
