### ISSUE TITLE
GMA SDK 9.9.0 compatibility for AdMob Adapters

### ISSUE THREAD

**Issue by maddapper** [prebid/prebid-mobile-ios#682]
**Is your feature request related to a problem? Please describe.**
Currently, Prebid Mobile iOS SDK has a hard dependency to GMA SDK 8.5.0.

**Describe the solution you'd like**
As a publisher who uses Cocoapods, we would like to have Prebid Mobile iOS SDK compatible with GMA SDK 9.9.0 and, if possible, for all versions of GMA SDK 9.x.  

**Describe alternatives you've considered**
There is no alternative, as this is a hard dependency requirement.

**Additional context**
https://github.com/prebid/prebid-mobile-ios/blob/master/PrebidMobileAdMobAdapters.podspec#L47

**Comment by YuriyVelichkoPI** [comment]
Just a clarification note. 

It is a dependency for AdMob Adapters. Not for the core Prebid SDK. Publishers who do not need AdMob adapters or GAM Event Handlers shouldn't experience dependency manager issues since these libraries are optional for integration.

**Comment by YuriyVelichkoPI** [comment]
In any case, we'll update the dependency in the upcoming release.

**Comment by YuriyVelichkoPI** [comment]
docs changes: 
https://github.com/prebid/prebid.github.io/commit/544e558fa6fea03e1121d60c306fa4c44c59ccf4
