### ISSUE TITLE
The `instl` filed should be `1` for full screen ad units in Original API

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#701]
## Description 

The bid request for an Interstitial ad unit for Original API doesn't fill the `instl` field with `1`: 

The sample of 'imp` object from the request from the DemoApp Swift -> GAM Simple Interstitial

```
"imp": [{
		"banner": {
			"format": [{
				"h": 852,
				"w": 393
			}]
		},
		"clickbrowser": 0,
		"displaymanager": "prebid-mobile",
		"displaymanagerver": "2.0.3",
		"ext": {
			"context": {
				"data": {}
			},
			"prebid": {
				"storedauctionresponse": {
					"id": "response-prebid-display-interstitial-320-480"
				},
				"storedrequest": {
					"id": "imp-prebid-display-interstitial-320-480"
				}
			}
		},
		"id": "51A0AA0D-9A58-40E2-973B-A2E6124C31DE",
		"instl": 0,
		"secure": 1
	}
```

## Objectives

- Make sure that all interstitial ad units set `instl` to `1`
- Add unit tests for the missed cases

**Comment by matrad** [comment]
@YuriyVelichkoPI do you have a plan when this will be released in a new version (cocoapod)?

**Comment by matrad** [comment]
@YuriyVelichkoPI We saw another issue in the Interstitial Behaviour:

With regards to the interstitial ad unit, we now see that the instl parameter is populated with the correct value (1), but the request still doesn't include valid sizes (there are only the device's screen dimensions instead). Using minWidthPerc & minHeightPerc will fix this, but these parameters are not present in the request (we'd expect to see them under ext.prebid.interstitial as in [this example](https://docs.prebid.org/prebid-server/features/pbs-interstitials.html)).


![image](https://user-images.githubusercontent.com/660903/202818015-a3c2ae21-8275-4936-a631-bf33b241e653.png)

**Comment by YuriyVelichkoPI** [comment]
Hi @matrad! 

Yes, it looks like serious regression as well. Please, follow #721 to track the fix. It will be introduced in the next release early next week.
