### ISSUE TITLE
 Design the consistent UI for iOS and Android demo applications

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#704]
## Background

The current views of the Demo apps are:

|iOS (Swift)|iOS (ObjectiveC)|Android (Kotlin)|Android (JAVA)|
|-----------|-----------------|---------------|---------------|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/21169695/199767956-7c9174ba-2b0f-44bc-927d-c2dff47718af.png">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/21169695/199768464-6b3b648d-2dab-4f0b-a29a-1000d401d278.png">| <img width="200" alt="image" src="https://user-images.githubusercontent.com/21169695/199769376-fa1791aa-87c5-41ac-8fce-e9ee6a7298b8.png">| <img width="200" alt="image" src="https://user-images.githubusercontent.com/21169695/199769943-7143d484-4df1-4c35-9339-47377eaa9c7d.png">|

In addition we have Internal Test Apps on iOS and Android
|iOS|Android|
|---|--------|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/21169695/199774674-00ef75c1-6357-4dfb-9ef7-6ca44438a047.png">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/21169695/199772200-6be4242d-a269-4e45-badf-8c6f8ad4b42e.png">|

As we see the UI/UX is pretty inconsistent. It is not so bad for the internal and demo apps but it confuses not less than inconsistent code base and makes publishers investigate the behaviour. 

## Motivation

We should provide publishers a similar experience on all platforms and app kinds, so they do not investigate different UIs and app architectures but study the integration of the Prebid SDK.

## Description  

Developing the SDK, the team primarily works with the Internal Test Apps. And we find their UI pretty convenient. It's a bit overloaded right now, but in Demo Apps we do not need as many controls as we use in the test apps. But the apps provide a straightforward way to find and run the needed examples.  

So we should update the UI for all other apps in the same style. 

The core idea is that publishers can do the following things:
- see all available examples in the general list
- filter the cases by the integration type (In-App, GAM, MAX)
- filter the cases by the ad format 
- search the needed example by name
- customize SDK settings (user consent, user data, refresh rate)

## Objectives

The main screen should contain integration examples with the following sections 
    - `Navigation Bar`
      - `Title` with current navigation selection 
      - The `Search Bar`
      - The selection for the `Integration Kind`
      - The selection for the `Ad Format`
    - The list of filtered examples

<img width="200" alt="Screenshot 2022-11-04 at 10 25 37" src="https://user-images.githubusercontent.com/21169695/199927742-81e3c3ec-5352-4325-a64d-fc694e38ed5c.png">

The `Tab Bar` is not needed for now. Later we will add the ability to customize the behavior via the additional settings screen. But now it is out of scope. And the Tab Bar widget doesn't look convenient for such an app. 

The selection controls should be implemented via drop-down (pull-down buttons) and contain the following items:

- `Integration Kind`:
   - GAM (Original API)
   - No Ad Server (Rendering API)
   - GAM (Rendering API)
   - AdMob (Rendering API)
   - MAX (Rendering API)
- `Ad Format`:
  - Display Banner
  - Video Banner
  - Display Interstitial
  - Video Interstitial
  - Rewarded Video
  - Native
  - In-stream video

<img width="267" alt="image" src="https://user-images.githubusercontent.com/21169695/199931436-49cbda1d-ff22-4a8d-90c4-0545cadeb515.png">

The title of the Navigation Section should display the text 'Prebid Demo Swift/ObjectiveC/JAVA/Kotlin' on the screen with the list of test cases and the name of the particular case on the demonstration screen f.e `Original API: Banner 320x50` 

Tapping on the example in the list should lead to the demonstration screen of the selected case.

**Comment by ValentinPostindustria** [comment]
![изображение](https://user-images.githubusercontent.com/72038591/200827585-4cf5201a-cad4-4401-b9f8-da701c8b5dee.png)

![изображение](https://user-images.githubusercontent.com/72038591/200827526-d0afefa7-8e0c-40f9-8a0c-e76a19898cb2.png)
