### ISSUE TITLE
Design a new Demo App Architecture

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#705]
## Motivation

Make integration examples convenient and self-descriptive. 

Our goal is to introduce one file/controller for each integration case. The codebase of the integration case should be compact and commented. Users should focus only on the code related to the particular integration case during studying. 

## Objectives

- Design the scalable app architecture, which will allow adding and demonstrating self-descriptive integration examples.  
- Introduce the policy for adding new examples
- Introduce tasks for refactoring the current code base of the demo apps

**Comment by OlenaPostindustria** [comment]
[IntegrationCase](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/IntegrationCase.swift)
<img width="478" alt="image" src="https://user-images.githubusercontent.com/92721590/200863193-f2483f9b-48d5-4119-a4ac-aae780206a27.png">

`IntegrationCase` has 4 properties:
- title
- [integrationKind](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/IntegrationKind.swift)(enum)
- [adFormat](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/AdFormat.swift)(enum)
- viewController:  unique integration case controller

Integration case title template: 
`[AdServer] [AdFormat] [Size] (Original API)`
- [AdServer]: In-App, GAM, AdMob, MAX
- [AdFormat]: Display Banner, Video Banner, Display Interstitial, Video Interstitial, Rewarded, Native, In-stream Video
- [Size]: creative size (f.e. 320x50)
- (Original API) - only for test cases built using original api

An example of integration case viewController is [here](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/Examples/OriginalAPI/OriginalBannerDisplayViewController.swift). 

Integration case view controller can be inherited from one of the base view controllers(f.e. [BannerBaseViewController](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/Examples/BaseViewControllers/BannerBaseViewController/BannerBaseViewController.swift)). Base view controllers provide default controls to show ad(f.e. banner view, loadAd button for interstitials etc). 


[IntegrationCaseManager](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/IntegrationCaseManager.swift) is responsible for storing integration cases. All cases will be populated in table view.
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/92721590/200863662-e5648f93-bac1-4bac-af99-840b9b7948b5.png">

**Comment by OlenaPostindustria** [comment]
[IntegrationCase](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/IntegrationCase.swift)
```swift
struct IntegrationCase {
    let title: String
    let integrationKind: IntegrationKind
    let adFormat: AdFormat
    let viewController: UIViewController
}
```
[integrationKind](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/IntegrationKind.swift)
```swift
enum IntegrationKind: CustomStringConvertible, CaseIterable {
    
    case originalGAM
    
    case renderingInApp
    case renderingGAM
    case renderingAdMob
    case renderingMAX
    
    var description: String {
        switch self {
        case .originalGAM:
            return "GAM (Original API)"
        case .renderingInApp:
            return "In-App (Rendering API)"
        case .renderingGAM:
            return "GAM (Rendering API)"
        case .renderingAdMob:
            return "AdMob (Rendering API)"
        case .renderingMAX:
            return "MAX (Rendering API)"
        }
    }
}
```
[adFormat](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/AdFormat.swift)(enum)
```swift
enum AdFormat: CustomStringConvertible, CaseIterable {
    
    case bannerDisplay
    case interstitialDisplay
    
    case bannerVideo
    case interstitialVideo
    
    case rewarded
    case native
    
    case instreamVideo
    
    var description: String {
        switch self {
        case .bannerDisplay:
            return "Display Banner"
        case .interstitialDisplay:
            return "Display Interstitial"
        case .bannerVideo:
            return "Video Banner"
        case .interstitialVideo:
            return "Video Interstitial"
        case .rewarded:
            return "Rewarded"
        case .native:
            return "Native"
        case .instreamVideo:
            return "In-stream Video"
        }
    }
}
```

Integration case title template: 
`[AdServer] [AdFormat] [Size] (Original API)`
- [AdServer]: In-App, GAM, AdMob, MAX
- [AdFormat]: Display Banner, Video Banner, Display Interstitial, Video Interstitial, Rewarded, Native, In-stream Video
- [Size]: creative size (f.e. 320x50)
- (Original API) - only for test cases built using original api

An example of integration case viewController can be found [here](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/Examples/OriginalAPI/OriginalBannerDisplayViewController.swift). 

Integration case view controller can be inherited from one of the base view controllers(f.e. [BannerBaseViewController](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/Examples/BaseViewControllers/BannerBaseViewController/BannerBaseViewController.swift)). Base view controllers provide default controls to show ad(f.e. banner view, loadAd button for interstitials etc). 


[IntegrationCaseManager](https://github.com/prebid/prebid-mobile-ios/blob/feature/refactor-domo-apps/Example/PrebidDemo/PrebidDemoSwift/IntegrationCaseManager.swift) is responsible for storing integration cases. All cases will be populated in table view.
```swift
struct IntegrationCaseManager {
    
    static var allCases: [IntegrationCase] = [
        IntegrationCase(
            title: "GAM Display Banner 320x50 (Original API)",
            integrationKind: IntegrationKind.originalGAM,
            adFormat: .bannerDisplay,
            viewController: OriginalBannerDisplayViewController(bannerSize: CGSize(width: 320, height: 50))
        )
    ]
}
```
