### ISSUE TITLE
Refactor the public documentation

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#706]
## Motivation

Introduce consistent Prebid Mobile documentation.

## Background 

The current documentation for Prebid Mobile consist of two parts:

- Original documentation for bid-transporting SDK (Original API)
- Documentaion for the integration of the Rendering API

The introduction of the Rendering API docs as a standalone section was made intentionally in order not to confuse publishers who used the original API. Such publishers shouldn't have changed anything in their setup after updating to 2.0, so the new docs could harm them by disrupting the accustomed approaches. 

Now we see that publishers studying the benefits and perspectives of Rendering API suffer from incomplete descriptions of the whole solution. On the other hand, publishers, SSPs, and DSPs who use the Original API  are missing an important feature that can increase monetization efficiency. And both of them do not have a comprehensive description of what Prebid SDK is, how it can be used, and what potential has. 

Moreover, the documentation is outdating from day to day. So the necessity for the reworking of documentation has become critical. 

## Objectives

- Update the original docs 
- Merge the docs for Rendering API and Original API
- Introduce the comprehensive description of the SDK and its satellite (Adapters and Event Handlers) solution and integration scenario

**Comment by YuriyVelichkoPI** [comment]
Progress tracking:

- REMOVE docs for legacy deprecated API
- MOVE the For Contributors article to the General Section

**Comment by huanzhiNB** [comment]
How's the progress on this? The doc for mobile rendering api is gone, I cannot find it since Feb 2023, the link will redirect to other pages or 404. Is there any plan to restore it?

**Comment by YuriyVelichkoPI** [comment]
Hi @huanzhiNB ! The docs for Rendering API are migrated to the sections for iOS and Android, respectively. 

<img width="282" alt="image" src="https://user-images.githubusercontent.com/21169695/216538078-d26efbff-3ed2-4fec-8389-ed41299a61ae.png">

Follow the integration kind that you are interested in. 

I'm closing this ticket because the unification of the docs has been finished. Let me know here or thru any other channel what info is unclear or has gaps so we can improve certain pages.
