### ISSUE TITLE
Build issue on travis-ci with 0.3

### ISSUE THREAD

**Issue by nanek** [prebid/prebid-mobile-ios#71]
I'm trying to upgrade to 0.3. I'm having an issue with getting this pod to build on travis-ci.

```
Warning: Multiple build commands for output file /Users/travis/Library/Developer/Xcode/DerivedData/epxvguudllrmhdayahonuxcmvthc/Build/Products/Debug-iphonesimulator/PrebidMobile/PrebidMobile.framework/Headers/PrebidMobile-umbrella.h
```

I see a similar warning locally, however it still builds. In the pod, it looks like there are two PrebidMobile-umbrella.h files, one in the root and one under Supporting Files.

On travis-ci it throws the warning then fails to build with the following. It's possible it is something specific to my setup in which case you can ignore this, however I'm posting in case this does sound familiar and is something wrong with the pod itself. Thanks!

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/PrebidMobile-umbrella.h"
        ^
/Users/travis/Library/Developer/Xcode/DerivedData/epxvguudllrmhdayahonuxcmvthc/Build/Products/Debug-iphonesimulator/PrebidMobile/PrebidMobile.framework/Headers/PrebidMobile-umbrella.h:14:9: error: 'PBServerRequestBuilder.h' file not found
#import "PBServerRequestBuilder.h"
        ^
/Users/travis/build/SDMopubAdView.swift:11:8: error: could not build Objective-C module 'PrebidMobile'
import PrebidMobile
```

**Comment by ppuviarasu** [comment]
We have released a new version of the SDK. Can you test the same & let us know if this solves your problem
