### ISSUE TITLE
Discuss LMT and ios 14.5

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-mobile-ios#717]
This is a followup to #1699 -- the hack Prebid Server did to support setting the `lmt` flag based on various other ORTB fields.

First, we found a bug in PBS-Java where an existing `lmt` field takes precedence over the workaround logic. This is not the case with PBS-Go, so we'll fix it.

But while reading the issue, there's a note that I need the mobile committee to consider... heads up @mittal-ank :

```
When Apple mandates pubs integrate into ATTS, we will have to change the logic slightly to read for version 14.5 (likely the next version they will start) to set LMT = 1 when it's unspecified. This was dictated by Apple. Until then unspecified is treated as authorized until then.
```

**Comment by YuriyVelichkoPI** [comment]
currently, the SDK is working according to the scenario described in #319
