### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#718]
## Objectives

Need to investigate and fix warnings in the Xcode project

<img width="250" alt="image" src="https://user-images.githubusercontent.com/21169695/202671023-d53fc2ba-9350-4ea1-88d0-4e0cd3803a72.png">

Also, please pay attention to new runtime warnings introduced in Xcode 14

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/21169695/202670869-823bb26a-c6b5-4425-aad0-465c8411e352.png">

**Comment by OlenaPostindustria** [comment]
`This method should not be called on the main thread as it may lead to UI unresponsiveness.` runtime errors are caused by GMA SDK. We can't fix them.
