### ISSUE TITLE
could not find module 'PrebidMobile' for target 'arm64-apple-ios-simulator'

### ISSUE THREAD

**Issue by felixkrautschuk** [prebid/prebid-mobile-ios#723]
**Describe the bug**
When adding the following to my Podfile:
`pod 'PrebidMobileAdMobAdapters', '2.0.4'`
I am not able to build the project anymore on iOS Simulator.

> Xcode build...
> /Users/felixkrautschuk/Downloads/ns-ios-prebid/platforms/ios/Pods/PrebidMobileAdMobAdapters/EventHandlers/PrebidMobileAdMobAdapters/Sources/AdMobMediationBannerUtils.swift:17:8: error: could not find module 'PrebidMobile' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: /Users/felixkrautschuk/Downloads/ns-ios-prebid/platforms/ios/build/Debug-iphonesimulator/PrebidMobile/PrebidMobile.framework/Modules/PrebidMobile.swiftmodule
> import PrebidMobile
>        ^
> <module-includes>:103:9: note: in file included from <module-includes>:103:
> #import "Headers/PrebidMobile-Swift.h"
>         ^
> Command SwiftCompile failed with a nonzero exit code
> ** BUILD FAILED **
> 
> Unable to apply changes on device: D0F8FCC1-6E5E-43E3-A95B-E3E080CC3D21. Error is: Command xcodebuild failed with exit code 65.

Running the project on physical device works as expected.

When adding the _PrebidMobile_ to my Podfile instead of _PrebidMobileAdMobAdapters_, the project is getting built for ios simulator as expected. 

I am working on Macbook Pro 2019 (Intel).

**To Reproduce**
none

**Expected behavior**
Projects with PrebidMobileAdMobAdapters should be able to be built for simulator and device.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0.1 (22A400)

**Smartphone (please complete the following information):**
 none

**Additional context**
We are building our app using the NativeScript framework and we know that there is no official support for that framework on your side, but we hope that you can help us anyway.

**Comment by YuriyVelichkoOpenX** [comment]
Hi @felixkrautschuk! 

I would like to clarify some details about your integration. If you want to integrate Prebid with AdMob, you should add both pods to your project:
- `PrebidMobile` - the core Prebid SDK
- `PrebidMobileAdMobAdapters` - the mediation adapters for the AdMob, which has a dependence to `PrebidMobile`

Do you have both pods in your Podfile and see the described error?

**Comment by felixkrautschuk** [comment]
@YuriyVelichkoOpenX thanks for your reply.

I added both pods and still se the same error.

**Comment by YuriyVelichkoPI** [comment]
tahnks @felixkrautschuk. We added this ticket to the backlog for the next release. @OlenaPostindustria will take a look as soon as possible.

**Comment by OlenaPostindustria** [comment]
Hi, @felixkrautschuk! We couldn't reproduce this issue. 
We tested both on Intel-based and M1-based Mac, Xcode 14.1

Here is our test project: 
[PrebidTest.zip](https://github.com/prebid/prebid-mobile-ios/files/10075472/PrebidTest.zip)

**Comment by YuriyVelichkoPI** [comment]
@felixkrautschuk could you try to build and run the project which Olena has shared?

**Comment by felixkrautschuk** [comment]
@YuriyVelichkoPI @OlenaPostindustria yes I was able to run the provided test project, thank you.
So that means that the NativeScript framework is not working correctly at one point.

I just don't understand why NativeScript can handle the core pod (PrebidMobile), but not the PrebidMobileAdMobAdapters (or even PrebidMobileMAXAdapters).

**Comment by YuriyVelichkoPI** [comment]
Hi @felixkrautschuk ! Any updates about the issue?

**Comment by felixkrautschuk** [comment]
@YuriyVelichkoPI sorry, I totally forgot to provide latest updates here.

The NativeScript team provided a fix on their side, so now I am able to build the NativeScript project on iOS using the Prebid mobile sdk.
I'm closing this now. Thank you for your help.

**Comment by YuriyVelichkoPI** [comment]
Great news! Thanks for the update!
