### ISSUE TITLE
Failed to render ad due to request not stubbed

### ISSUE THREAD

**Issue by hugolm84** [prebid/prebid-mobile-ios#733]
Hi! 
Using PrebidDemoSwift and its `GAMOriginalAPIDisplayBannerViewController`, I get `Prebid demand fetch for GAM Prebid demand fetch successful` but the bannerView fails to render due to `Could not load request successfully: This can happen if the request was not stubbed, or if the stubs were removed before this request was completed (due to asynchronous request loading).`

The Impression URL provided by prebid-server is renderable in ios browser.

Error:
````
GAM did fail to receive ad with error: Error Domain=com.google.admob Code=2 "The operation couldn't be completed. (kPBTestHTTPStubURLProtocolExceptionKey error 1.)" UserInfo={NSLocalizedDescription=The operation couldn't be completed. (kPBTestHTTPStubURLProtocolExceptionKey error 1.),
````

Any suggestion how to mitigate this?

**Comment by YuriyVelichkoPI** [comment]
Hi @hugolm84! 

It looks like something works wrong for you in GMA SDK integration. We'll take a look

**Comment by YuriyVelichkoPI** [comment]
@hugolm84 please, check the app on the master branch. The bug should be fixed there.
