### ISSUE TITLE
Targeting.shared.addUserKeywords Does not Work in iOS

### ISSUE THREAD

**Issue by Kowshickkarthick** [prebid/prebid-mobile-ios#753]
**Describe the bug**
Targeting.shared.addUserKeywords does not work in iOS

**To Reproduce**
Tried setting keywords in Prebid Mobile SDK iOS as per doc in below link:
https://docs.prebid.org/prebid-mobile/pbm-api/ios/pbm-targeting-ios.html#user-keywords
When making an Ad request, User Keywords are not seen in JSON body.

Ex: 
var keywordsSet = Set<String>()
keywordsSet.insert("kv_test=1,23")
keywordsSet.insert("prebidsamplekey=prebidsamplevalues")
Targeting.shared.addUserKeywords(keywordsSet)

**Expected behavior**
When User Keywords are set it should be sent in Prebid OpenRTB JSON Request body.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone14
 - OS: 16.1.1
 - Prebid SDK Version: 2.0.3

**Additional context**
This works fine in Android.
[android_request_keywords.txt](https://github.com/prebid/prebid-mobile-ios/files/10347101/android_request_keywords.txt)

**Comment by mmullin** [comment]
@YuriyVelichkoPI FYI

**Comment by YuriyVelichkoPI** [comment]
Hi @Kowshickkarthick ! 

Just want to let you know that we are working on reviewing and verification of PR #685 to include it in the next SDK version, and it is delaying the release of the fix for this issue. 

We plan to release it early next week.
