### ISSUE TITLE
Problems to add Prebid Pod

### ISSUE THREAD

**Issue by EnricMob** [prebid/prebid-mobile-ios#767]
**Describe the bug**
I'm trying to add PrebidMobile 2.0.6 for our iOS proyect and I receive an error from git telling us: 
- Using swift static libraries with custom maps is currently not supported. Please buil "PrebidMobile as a framework or remove the custom module map.

We don't want to add Prebid as a framework and we don't know if the problem is something related with old libraries but i want to add a pod but we can't.

**To Reproduce**
1. Trying to do: Pod install PrebidMobile 2.0.6

**Expected behavior**
Pods installed successfully 

**Screenshots**
<img width="568" alt="Screenshot 2023-01-20 at 09 44 44" src="https://user-images.githubusercontent.com/72864625/213653331-ffbc2013-166e-4953-ab05-ffea3aae8e85.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YuriyVelichkoPI** [comment]
Hi @EnricMob !

Please try to integrate SDK version - `2.0.7`. It supports integration without `use_frameworks`.

**Comment by EnricMob** [comment]
Solved thanks!!!
