### ISSUE TITLE
SDK First Party support

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-mobile-ios#785]
**Describe the bug**
We were alerted in https://github.com/prebid/prebid-server/issues/2557 that the SDK (both ios and android) is using an old location for adunit-specific first party data. imp.ext.context.data has been long deprecated and should be just imp.ext.data.

e.g.
https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/BasicParameterBuilder.java#L364

So to be clear, the first party data rules for SDK should be the same as they are for Prebid.js:
1) global contextual data goes on site.ext.data
2) global user-related data goes on user.ext.data
3) adunit/imp specific data goes on imp.ext.data
4) bidder-specific data can be defined on ext.prebid.bidderconfig, but I'm thinking that's out of scope for SDK.

**Comment by OlenaPostindustria** [comment]
Hi @bretg!

I came across ad unit context keywords, which go on `imp[].ext.context.keywords`. Do we need to transfer them as well on `imp[].ext.keywords` or they are no longer in use?

**Comment by bretg** [comment]
Hi @OlenaPostindustria - not sure the SDK needs to have a separate way to enter adunit-specific keywords, but right, if such a thing is desired,  they would also go on imp[].ext.keywords
