### ISSUE TITLE
Remove bitcode support from build script

### ISSUE THREAD

**Issue by OlenaPostindustria** [prebid/prebid-mobile-ios#815]
### Motivation 
Bitcode started being deprecated since Xcode 14 (September 12th, 2022).  From Apple’s [release note](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes) of Xcode 14:

> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the **App Store no longer accepts bitcode submissions from Xcode 14**.

> **Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode:** “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.”

> **The capability to build with bitcode will be removed in a future Xcode release.** IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. 

### Objectives 
Remove all code dedicated to building frameworks with bitcode from `buildPrebidMobile.sh`.

**Comment by YuriyVelichkoPI** [comment]
Is still allowed to submit apps with Xcode 13 https://developer.apple.com/support/xcode. Hence, with bitcode. If so - let's address the zsh script issue for now.

**Comment by OlenaPostindustria** [comment]
Starting April 25, 2023 apps submitted to the App Store must be built with Xcode 14.1 or later. More details can be found [here](https://developer.apple.com/news/?id=jd9wcyov).
