### ISSUE TITLE
404 errors noticed in server communication

### ISSUE THREAD

**Issue by iAgentur** [prebid/prebid-mobile-ios#82]
We such network calls invoked by the prebid SDK 0.3:

Example request:
`GET /pbc/v1/cache?uuid=EDE22F50-5F9A-48C8-B5B6-93C69D638C48 HTTP/1.1
Host: prebid.adnxs.com
Origin: https://pubads.g.doubleclick.net
Connection: keep-alive
Accept: */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15F79;native-20minDE;app-ios-smartphone-1`

Respective Response:
`HTTP/1.1 404 Not Found
Server: nginx/1.11.10
Date: Tue, 19 Jun 2018 11:46:12 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 64
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://pubads.g.doubleclick.net
Vary: Origin
X-Content-Type-Options: nosniff
X-Rate-Limit-Duration: 1s
X-Rate-Limit-Limit: 100
X-Rate-Limit-Request-Forwarded-For: 185.9.18.84
X-Rate-Limit-Request-Remote-Addr: 172.16.91.0:49026
Connection: keep-alive

No content stored for uuid=EDE22F50-5F9A-48C8-B5B6-93C69D638C48`

The question now is, are such 404 server errors intended?
Are cache misses intentionally returned as 404 errors or does this require adjustments on either SDK or server side?

**Comment by ppuviarasu** [comment]
We have updated the caching logic & got a new release today. Can you check the same & open a new ticket if there are any caching issues.
