### ISSUE TITLE
0.4 not building due to non-public file remains

### ISSUE THREAD

**Issue by qkzhu** [prebid/prebid-mobile-ios#83]
### [Issue 73](https://github.com/prebid/prebid-mobile-ios/issues/73) from 0.3 remains on 0.4.

The issue is compile error for `'PBServerRequestBuilder.h' file not found`
#### How to replicate the issue:
* Created a new Swift project with pod file: 
```
target 'PrebidTest' do
  use_frameworks!
  pod 'PrebidMobile'
end
```
* Import `PrebidMobile` in any of you Swift file: `import PrebidMobile` and build.

#### The cause 
It cased by including `PBServerRequestBuilder.h` in umbrella header while it's not `public access`.

#### Temporary manual fix
After `pod install`, change `PBServerRequestBuilder.h` to `public` access.

#### Suggest fix
Maybe you can remove `#import "PBServerRequestBuilder.h"` from umbrella file as `PBServerRequestBuilder` seems to be only used internally.

**Comment by anwzhang** [comment]
Hi @qkzhu,
Would you mind submitting a PR to fix this?

Best,
Wei

**Comment by qkzhu** [comment]
Hi @anwzhang,  PR #92  submitted.

**Comment by ptomasroos** [comment]
This is now resolved, please close
