### ISSUE TITLE
Banner Size issue after correction with AdViewUtils. findPrebidCreativeSize

### ISSUE THREAD

**Issue by matrad** [prebid/prebid-mobile-ios#838]
Hello,

in the Prebid Documentation it says that in the `bannerViewDidReceiveAd` callback we should call the `AdViewUtils.findPrebidCreativeSize` method, but we have the Issue that:

 - We request a Banner for the Ad-Unit-Id `stol7_hp_sky` with 320x50 px of size
 - We get a Feedback from the `bannerViewDidReceiveAd` delegate callback from GAD-Manager with the Size of `320x50px` what is OK & is correct for the displayed banner.
 - Then we ask the method `AdViewUtils.findPrebidCreativeSize` to check if the size is correct, and we get from this delegate a size of `300x250`.
 - In our case we change the banner-size and it's displayed wrong, see the screenshot - because the 320x50 banner is displayed in a 300x50 - rect (The Red-Area is the View containing the BannerView)

<img src="https://user-images.githubusercontent.com/660903/235970247-28821e42-b2e9-47e7-9d51-13cc7f7676de.png"  width="231" height="500">

Sometimes we also receive this feedback from the `findPrebidCreativeSize` callback:
```
["adview error findPrebidCreativeSize Optional(\"/2273514/stol7_hp_sky\") bannerAdSize=GADAdSize(size: (320.0, 50.0), flags: 0), error=Error Domain=com.prebidmobile.ios Code=140 \"The HTML doesn\'t contain a size object\" UserInfo={NSLocalizedDescription=The HTML doesn\'t contain a size object}"]
``` 
In this case it's working, because the `AdViewUtils.findPrebidCreativeSize` does not get a valid callback and the banner is not corrected.

Here is the Charles-Log attached: https://www.dropbox.com/s/i0h19d4rhqw5jn3/charles-debug-stol.chls?dl=0
(There may also 1-2 ad request what does not belongs to this issue, the correct one is `24524-app--Stol-App-stol7_default_sky`

Can you tell us where the issue is? Is it SDK related?

**Comment by YuriyVelichkoPI** [comment]
Hi @matrad ! Thanks for the detailed report. We'll take a look at it in the nearest few days and get back to you with the results.

**Comment by YuriyVelichkoPI** [comment]
@matrad, at first glance, I can say that the bid response for `24524-app--Stol-App-stol7_default_sky` returns the ad with size `300x250`.  With respective keyword: 

```
"hb_size": "300x250"
```

The `findPrebidCreativeSize` determines the size by this keyword. 

So it needs to figure out why the bid contains incorrect size values.

**Comment by matrad** [comment]
@YuriyVelichkoPI so it means we need to speak with our analytics adapter magnite?

In our case each ad unit has multiple sizes declared an the Google GAM (Ad Manager) outputs the correct one. So there is not one correct size.

We already told Magnita that the size for this request may be incorrect and got this answer:

The MTOs for in app work slightly differently than for Web. 
Sizes declared in the MTO are used for GAM targeting and mapping purposes only. The sizes declared on the AMP page or Prebid SDK will determine the sizes requested from bidders in Prebid bid request
If the GAM line items used for your AMP or Mobile App demand are missing any sizes, you can add them by creating “dummy” MTOs with those sizes listed as the primary ad size and assigning the MTOs to “dummy” SRIDs to force Ad Server Config to add those sizes to the applicable line items’ targeting.
More information can be found below: 
https://resources.rubiconproject.com/resource/publisher-resources/demand-manager/demand-manager-media-type-config/
MTO = Media Type Object 

So if I understand this issue, the sdk behaviour is correct - we need to change something on our bidder's ad server or configuration, correct?

**Comment by YuriyVelichkoPI** [comment]
Yes, SDK retrieves the size from the bid response, and in this case, it is 300x250. 

As for me, the issue is that the bidder responds with the wrong size. I'm not sure how it is implemented on the PBS/Adapter/Bidder side, but the bidder should return the `320x50`, and this value should be placed in the bid response, and later SDK will process it respectively. 

I don't think that it depends on the GAM setup because the auction happens before the ad request to GAM.

**Comment by YuriyVelichkoPI** [comment]
Also, since the creative looks like a test one, I assume it can be just some copy-paste issue when the 320x50 creative code is put into the response 300x250 template. But it is just a guess.

**Comment by YuriyVelichkoPI** [comment]
Hi @matrad! Do you have any updates for this ticket?
