### ISSUE TITLE
Document test stored responses

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-mobile-ios#839]
As discussed in https://github.com/prebid/prebid.github.io/pull/4530, please document the definition for a set of test stored requests that are utilized by the demo apps.

The goal is to let publishers (or PBS host companies) insert this set of "prebid standard" stored requests so that demo apps can be pointed at the PBS and work.

Please use a prefix of "prebid-demo-" for each stored requests. e.g. "prebid-demo-300x50"

**Comment by YuriyVelichkoPI** [comment]
Hi @bretg ! We are working on this ticket and want to clarify what exactly you mean by "document". Should we add examples of prebid docs or put them in some folder in the repo and provide the publisher the link to this folder in the docs?

**Comment by YuriyVelichkoPI** [comment]
Hi @bretg ! So far we put the copies of stored impressions and stored requests into the folder in this repo. Now we should document them. 

Should we put the reference to the [folder with configs ](https://github.com/prebid/prebid-mobile-ios/tree/master/Example/PrebidDemo/stored-configs), or add the actual content to the doc pages?

**Comment by YuriyVelichkoPI** [comment]
The commit with changes to the docs: 
https://github.com/prebid/prebid.github.io/pull/4604/commits/b5cbd64677abfdd9af7904cf15c7cec8152e591e

**Comment by YuriyVelichko** [comment]
@OlenaPostindustria, need to apply some more clean-up work to stored responses: 

- remove win notifier `https: //prebid-server-test-j.prebid.org/win/prebid`
- use common Prebid creatives like `https://s3.amazonaws.com/files.prebid.org/creatives/prebid320x50.png`
- remove OMID tag. 

Please, apply these changes to all creatives used in the Demo Apps. If the same creative is used in the internal test app and utilized in tests that require some of the removed parts - introduce a separate creative for the internal test app.

**Comment by YuriyVelichkoPI** [comment]
@bretg, we've updated the samples of stored responses. So could you take a look, please:
https://github.com/prebid/prebid-mobile-ios/tree/master/Example/PrebidDemo/stored-configs/stored-responses

**Comment by bretg** [comment]
Thanks @YuriyVelichkoPI and @OlenaPostindustria . Doc PR merged. Looks like there's still an open related issue, but perhaps this issue can be closed?

**Comment by YuriyVelichkoPI** [comment]
Yes, I'll close this issue and another one. 

Thank you @bretg
