### ISSUE TITLE
DOC: restore the guide for creating GAM order for the In-App Native ads

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-ios#878]
## Motivation

Can't find this doc anymore

## Objectives

Need to restore the doc with description of GAM creative for In-App Native integration.

**Comment by YuriyVelichkoPI** [comment]
@bretg, I've found the needed info in the docs. 

The `In-App` section for the native ads contains the `Ad-Ops` information: 

https://docs.prebid.org/prebid-mobile/pbm-api/ios/ios-sdk-integration-gam-original-api.html#in-app-native

Does it make sense to move this section to: 
https://docs.prebid.org/adops/gam-native.html

**Comment by bretg** [comment]
Yes, if there's a special process for Ad Ops in setting up native on GAM, it ought to be in the AdOps section, and I suppose https://docs.prebid.org/adops/gam-native.html is as good as any.

We'll leave this issue open until someone gets a chance to do that.

**Comment by YuriyVelichkoPI** [comment]
doc PR: https://github.com/prebid/prebid.github.io/pull/5099

**Comment by YuriyVelichkoPI** [comment]
The PR is merged
