### ISSUE TITLE
Support GMA SDK 10.7.0 & 10.8.0 

### ISSUE THREAD

**Issue by OlenaPostindustria** [prebid/prebid-mobile-ios#886]
## Motivation
A new GMA SDK version was released.

## Objectives
- investigate changes in GMA SDK 10.7.0 and 10.8.0;
- if needed, update the behavior in Original API, AdMob Adapters, and GAMEventHandlers respectively to the changes in the GMA SDK.

**Comment by YuriyVelichkoPI** [comment]
Doc PR: https://github.com/prebid/prebid.github.io/pull/4763
