### ISSUE TITLE
Prebid mobile framework package fails Apple upload validation

### ISSUE THREAD

**Issue by maddapper** [prebid/prebid-mobile-ios#891]
**Describe the bug**
Uploading builds to AppStore results in validation errors:
`*** Error: Asset validation failed The bundle 'Payload/SwingU.app/Frameworks/PrebidMobile.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString.`
`*** Error: Asset validation failed This bundle Payload/SwingU.app/Frameworks/PrebidMobile.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. `

**To Reproduce**
1. Bitrise Apple Developer Connection with API key found
Uploading - App.ipa ...
$ xcrun "altool" "--upload-app" "-f" "/Users/vagrant/deploy/App.ipa" "--type" "ios" "--apiKey" "XXXXXXX" "--apiIssuer" "xxxxxx-xxxx-xxxx-xxxx....."

**Expected behavior**
AppStore Upload validation should return success.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS, MacOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by OlenaPostindustria** [comment]
Hi, @maddapper!
What `PrebidMobile` version do you use and how do you integrate it?

**Comment by maddapper** [comment]
2.1.2 via Cocoapods

**Comment by maddapper** [comment]
@OlenaPostindustria ok thanks for checking, this issue is now resolved.   please go ahead and close this ticket.
