### ISSUE TITLE
Support impression-level GPID parameter

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-mobile-ios#925]
**Is your feature request related to a problem? Please describe.**

Publishers want to be able to specify the Global Placement ID (GPID) on the ad call. This is not currently possible through the SDK.

**Describe the solution you'd like**

Publishers should be able to specify the GPID for each impressions, and it gets passed to Prebid Server as imp[].ext.gpid

Originally, I was hoping that we could make this a generic ORTB parameter interface, but conversations around issue https://github.com/prebid/prebid-mobile-ios/issues/877 revealed that the size of that request was slowing this smaller enhancement.

**Comment by bretg** [comment]
Thanks for the enhancement, but this needs a docs update... how do app developers make use of this?

**Comment by YuriyVelichkoPI** [comment]
Doc PR: https://github.com/prebid/prebid.github.io/pull/4927

**Comment by bretg** [comment]
Sorry - I prematurely merged the original docs. Reverted. New PR https://github.com/prebid/prebid.github.io/pull/4929 . Since the docs are waiting for release, will close the issue.
