### ISSUE TITLE
Privacy Manifest Required Reason API update

### ISSUE THREAD

**Issue by willk37** [prebid/prebid-mobile-ios#963]
Apple is going to start requiring every app and third-party SDK to provide reasoning for using certain APIs by May 1, 2024. It looks like this SDK is using NSUserDefaults which is one of those specified APIs and needs to be [documented](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) in a [privacy manifest file](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).

Thanks!

**Comment by YuriyVelichkoPI** [comment]
Hi @willk37 ! 

Please take a look at the section in FAQ: https://docs.prebid.org/faq/prebid-mobile-faq.html#does-sdk-provide-an-apple-privacy-manifest.

**Comment by willk37** [comment]
@YuriyVelichkoPI Thanks for the quick response!
