### ISSUE TITLE
GPP & GPP SID values in ext

### ISSUE THREAD

**Issue by ankit-thanekar007** [prebid/prebid-mobile-ios#967]
In the current release 2.2.0, I don't see the changes that were added in this PR #736 . In the PR the changes were added to add values of GPP and GPP SID inside `ext`.  I wanted to understand if they were missed or is there a reason for them being not in release ?

[[prebid-mobile-ios/PrebidMobile/PrebidMobileRendering/Networking/Parameters/PBMBasicParameterBuilder.m]()](https://github.com/prebid/prebid-mobile-ios/blob/7034d236f71cc2dc9b506a567280be3e83836de8/PrebidMobile/PrebidMobileRendering/Networking/Parameters/PBMBasicParameterBuilder.m#L130)

**Comment by ankit-thanekar007** [comment]
@YuriyVelichkoPI @OlenaPostindustria ^

**Comment by YuriyVelichkoPI** [comment]
Hi @ankit-thanekar007 ! 

Gpp_sid is set few lines later: https://github.com/prebid/prebid-mobile-ios/blob/7034d236f71cc2dc9b506a567280be3e83836de8/PrebidMobile/PrebidMobileRendering/Networking/Parameters/PBMBasicParameterBuilder.m#L133

It was changes in the scope of: https://github.com/prebid/prebid-mobile-ios/pull/774

Do you mean that the fields are expected in the `ext` object?

**Comment by ankit-thanekar007** [comment]
@YuriyVelichkoPI Yes, but from the PR it seems it was changed for v2.6 of openrtb. https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#objectregs

Is that correct ?

**Comment by YuriyVelichkoPI** [comment]
@ankit-thanekar007 Yes, and such a mix of standards looks like an error to me. I was wrong in approving it because I didn't pay attention to differences in the RTB versions. 

So I'm asking - is it critical for you and SDK to return the support according to the 2.5 protocol?

**Comment by ankit-thanekar007** [comment]
Thanks @YuriyVelichkoPI , I think we're good here. Thanks !
